cookies = "bilibili.com_cookies.txt"
tempdir = "tmp"
cdn = 0
chunk-size = 4096

[vocaloid]
id = 467191862
flags.data = 1
flags.aiff = 1
flags.flac = 1
copy.base="F:\\OneDrive - 66CCFF\\Archives\\LuoTianyi.dev\\main"
copy.replace.dash="dash"
copy.replace.aiff="aiff"
copy.replace.flac="flac"
copy.replace.data="data"

[music]
id = 90169562
flags.data = 1
copy.base="F:\\OneDrive - 66CCFF\\Archives\\Bilibili"
copy.replace.dash="01-Music"
