create-time = 1497429887
publish-time = 1422954099
avid = 1954864
bvid = "BV1Vx411A7FL"
title = "【自制】伪物语OP3完善版（自配字幕）"
category = "MAD·AMV"
desc-base64 = "6Ieq5Yi277yM5paw5Lq656ys5LiA5qyh5oqV56i/KOS5i+WJjeaKlemUmeWMuuS6hi0gLSnvvIzlvojllpzmrKLnmoTkuIDpppbmtJfohJHmm7LvvIznu4jkuo7lv43kuI3kvY/nu5nokIzokIznmoTmnIjngavphbHphY3lrozlrozmlbTnmoTnmb3ph5Hov6rmlq/np5HvvIzlj6/mgJznmoTmnIjngavmlbTpg6jkvKrnianor63kuKrkurrml7bpl7Tov5jkuI3otrMz5YiG6ZKf77yM5peg5aWI5Y+q5pyJ5Yqg5YWl5Y6f5Lyq54mp6K+tT1Az77yM5biM5pyb5aSn5a625Zac5qyi44CC"
[[parts]]
cid = 3021708
name = ""
length = 246
resolution = "640x360"

[uploader]
uid = 6980843
name = "框框945"

[snapshot]
snapshot-time = 1613320694.2991138
danmakus-count = 46
likes-count = 190
favorites-count = 13
snapshot-by = "moe.lty.bgetlib/1.x"
