create-time = 1497420620
publish-time = 1404002610
avid = 1239074
bvid = "BV1ix411T7ge"
title = "波涛汹涌（苍蓝钢铁的琶音）【海军印象】＆【丝绸与钢】第7弹"
category = "MAD·AMV"
desc-base64 = "6Ieq5Yi2IOaEmuS9nOesrDflvLnlvIDmlrDlnZHvvIzlpKfmtbfljbDosaHnrKzkuIDlj5HjgILmm7Lnm67vvJrms6LmtpvmsbnmtozvvIjlkIzlkI3nlLXop4bliafkuLvpopjmm7LvvInkvZzmm7LvvJrlj7blsI/nurLjgILvvIjmi5nnoIHvvJpzbTIzODgxNjQy77yJ5pen5L2c6IGU5Yqo77yI56m677yJ77yaYXYxMjE2OTY2ICBhdjExNDM1NjbvvIjpmYbvvInvvJphdjkyODkxOCBhdjExMzQ2NDYgYXY4MDI4NTkgYXY2NjI0NjUgYXY1MTgyODEgYXY1MDUwMTMgYXY0NTQ4NDcg6L+b5Ye755qE5oqX5oiY77yaYXY4MzcwOTggYXY3MjgzMjcgYXY3MTAwMzcgYXY2ODE4MDA="
[[parts]]
cid = 1876775
name = ""
length = 120
resolution = "640x360"

[uploader]
uid = 322365
name = "江田岛健儿"

[snapshot]
snapshot-time = 1613320689.6886482
danmakus-count = 7
likes-count = 7
favorites-count = 1
snapshot-by = "moe.lty.bgetlib/1.x"
