create-time = 1497437568
publish-time = 1493610901
avid = 10227582
bvid = "BV11x411276T"
title = "叶小纲-波涛汹涌    中国海军故事_标清"
category = "音乐综合"
desc-base64 = "6L2s6L296Ieq5LyY6YW3CuS4reWbvea1t+WGm+iDjOaZr+eUteinhuWJp+azoua2m+axuea2jOeahOeJh+WktOabsu+8jOmSoueQtOWNj+Wlj+absuazoua2m+axuea2jOOAgg=="
[[parts]]
cid = 16896972
name = ""
length = 324
resolution = "320x246"

[uploader]
uid = 56393426
name = "老吕是猫司令"

[snapshot]
snapshot-time = 1613320688.8222628
danmakus-count = 0
likes-count = 4
favorites-count = 1
snapshot-by = "moe.lty.bgetlib/1.x"
