create-time = 1518512409
publish-time = 1518512407
avid = 19412189
bvid = "BV1PW411E7aS"
title = "【Yunomi】インドア系ならトラックメイカー【MV】"
category = "电音"
desc-base64 = "5L2c6K+NOiBZdW5vbWkK5L2c5puyOiBZdW5vbWkK57yW5puyL+a3t+mfszogWXVub21pCueugOS7i+ihpeWFhTog4oCc5YGH5pelUHJvamVjdOKAneesrOS4gOW8uQrljp/llLHvvJpOaWNhbW9xCuS4reaWh+Whq+ivje+8mlN0X+iJsuWkqgrkuK3mlofnv7vllLHvvJpIYW5zZXIgQVYxOTQwMTk1Mw=="
[[parts]]
cid = 31651157
name = ""
length = 202
resolution = "1920x1080"

[uploader]
uid = 267598802
name = "Yunomi_official"

[snapshot]
snapshot-time = 1613320682.5981715
danmakus-count = 681
likes-count = 19251
favorites-count = 16809
snapshot-by = "moe.lty.bgetlib/1.x"
