create-time = 1497429716
publish-time = 1425629824
avid = 2081169
bvid = "BV1Xx411A7Pm"
title = "【9人翻唱/拜年祭单投】Wonder zone中文填词"
category = "翻唱"
desc-base64 = "6Ieq5Yi2IOaLnOW5tOelreWNleaKle+8jOatjOWnrGlk77yI5LiN5YiG5YWI5ZCO6aG65bqP77yJ77ya5rC05puc5pel44CB5bCP5Y+4cHlvbuOAgeWciDnlnIg544CB5qGD5rKi44CB6Iy255CG55CG44CB5ous5Y+35ZCb44CBS29uYVl144CB6Zyy6JKC5Lid44CB5bCP6LGh77yM5pys5a625L2c5puy77ya5L2Q44CF5YCJ5pyJ5ZC+77yM5Lit5paH5aGr6K+N77yac2lyZW7vvIznlLvluIjvvJrmt7HmuIrvvIxQVu+8mnVw5Li777yM55uR552j77yaTnV1de+8jOmfs+mikeWQjuacn++8mumYv+mRq+OAguWkp+WutuaWsOeahOS4gOW5tOS5n+imgee7p+e7reWKquWKm35+fg=="
[[parts]]
cid = 3223661
name = ""
length = 233
resolution = "640x360"

[uploader]
uid = 6672592
name = "迷の益生菌"

[snapshot]
snapshot-time = 1613320696.7772264
danmakus-count = 204
likes-count = 922
favorites-count = 101
snapshot-by = "moe.lty.bgetlib/1.x"
