create-time = 1527923778
publish-time = 1527923778
avid = 24269294
bvid = "BV13W411N7Ji"
title = "【超清版】奇异恩典——《无问西东》中沈光耀为孤儿空投食物"
category = "影视剪辑"
desc-base64 = "5aWH5byC5oGp5YW477yM5rKB5YWl5b+D55Sw77yM5pel5pyI5bGx5bed77yM5ZCM6KeB44CC5Lmf5pu+5rCU6aaB77yM5bi46KKr6K+V54K877yM5L+h5b+D5bim6aKG77yM5ZCR5YmN44CC5Y6G57uP5Zuw6aG/77yM6Leo6L+H6Imw6Zmp77yM5oC75Lya5YaN6KeB77yM5pm05aSp44CC5L2g55qE5oGp5YW477yM6ZO65ruh5aSp6L6577yM5pyJ5b+D5Lq655yL5b6X6KeB44CCCui/memmluatjOabsuWwseaYr+iRl+WQjei1nue+juivl0FtYXppbmcgR3JhY2XnmoTkuK3mlofph43mlrDloavor43niYjvvIzmr4/lvZPmrYzmm7Llk43otbfml7bvvIzmsojlhYnogIDlsLHlsLHlho3mrKHkuLrlraTlhL/luKbmnaXpo5/nianlkozluIzmnJvvvIzluKbmnaXnpZ7nmoTmganlhbjjgIIKSGVyZSBvbiBlYXJ0aCBHb2QncyB3b3JrIG11c3QgdHJ1bHkgYmUgb3VyIG93bi4gQW1lbiEK5LiK5bid5Zyo5bCY5LiW55qE5bel5L2c5b+F5a6a5piv5oiR5Lus6Ieq5bex55qE5bel5L2c44CC6Zi/5Lus77yB"
[[parts]]
cid = 40692758
name = "纯演奏——第一次空投"
length = 79
resolution = "3840x1608"

[[parts]]
cid = 40692759
name = "孩子们合唱————第二次空投"
length = 126
resolution = "3840x1608"

[uploader]
uid = 114212970
name = "南径行山"

[snapshot]
snapshot-time = 1613320690.4913523
danmakus-count = 33
likes-count = 444
favorites-count = 223
snapshot-by = "moe.lty.bgetlib/1.x"
