create-time = 1497424591
publish-time = 1430366150
avid = 2271112
bvid = "BV1es411D7sW"
title = "【循环向】跟着雷总摇起来！Are you OK！"
category = "鬼畜调教"
desc-base64 = "6Ieq5Yi2IOWwj+S9nOWTge+8jOaKgOacr+WQq+mHj+S4jemrmO+8jOS4jeaIkOaVrOaEj+OAguW7uuiuruWFiOeci+WOn+eJiGF2MjI1NDMxMeOAgueci+S6humbt+aAu+eahOWPkeW4g+S8muaVtOS4quS6uumDvVJVT0vkuobvvIzlrabkuobov5nkuYjlpJrlubTnmoToi7Hor63lj6Ppn7Plhajlm57kuI3ljrvkuobjgILomb3nhLbmmK/oi7Hor63mrYzvvIzkvYbmiJHnm7jkv6HmmK/kuKrnorDov4foi7Hor63kuabnmoTogq/lrprpg73og73lkKzmh4LjgIJCR03vvJpBbmdlbGluYSBQU++8muWmguaenOacieWtl+W5leWQm+eci+WIsOeahOivneivt+W4ruW/meWcqDDigJg04oCZ4oCYMTIw5YiwMuKAmTfigJjigJkwMDDkuYvpl7TliqDkuKrlvqrnjq/vvIzpnIDopoHku6PnoIHlvLnluZXmjojmnYPnmoTor53or7fnp4Hkv6HmiLPmrbvmiJHvvIzljYHliIbmhJ/osKLvvIHmnaXlkKfvvIHkuLYowrDiiIDCsClBcmUgeW91IE9LPyjCsOKIgMKwKe++iQ=="
[[parts]]
cid = 3540266
name = ""
length = 132
resolution = "640x360"

[uploader]
uid = 609687
name = "Mr.Lemon"

[snapshot]
snapshot-time = 1613320692.1585004
danmakus-count = 181589
likes-count = 1060531
favorites-count = 1082237
snapshot-by = "moe.lty.bgetlib/1.x"
