create-time = 1534852855
publish-time = 1534852855
avid = 29919932
bvid = "BV1sW411Q7yu"
title = "君がいる世界へ 一花依世界 日文版 【鹿乃】"
category = "翻唱"
desc-base64 = "44GK44KB44Gn44Go44GG44CC44Gd44GX44Gm44CB57Sg5pW144Gq5LiW55WM44KS5pWZ44GI44Gm44GP44KM44Gm44GC44KK44GM44Go44GG77yBCgphdjI2NjU5MzY0CmF2Mjg2MzY1MjAKCuatjO+8mum5v+S5gyAgICAgIHdlaWJvIOKWtu+4jmthbm9fZGF5b+OAgOOAgOOAgFR3aXR0ZXLjgIDilrbvuI5rYW5vXzI1MjUgCumhjOWtl++8mumTreiogOWQmwrml6XmnKzoqp7mrYzoqZ7vvJpCS+Wwj+m5vwrli5XnlLvvvJpBS0FNRUlf6YqYCm1peGluZ++8mkNoYWtvCuOCqOODs+OCs+ODvOODie+8mkxTPV89IArjgrXjg53jg7zjg4ggeXV1cmkKCuiwouiwouaCqO+8gQrjg5Pjg6rjg5Pjg6rjgIF3ZWlib+OAgeODhOOCpOODg+OCv+ODvOOAgeOCpOODmeODs+ODiOOAgeOBneOCjOS7peWkluOBp+OCguOBn+OBj+OBleOCk+OBruW/nOaPtOOBruawl+aMgeOBoeOCkuWxiuOBkeOBpuOBj+OCjOOBpuWsieOBl+OBhOOBp+OBmeOAgg=="
[[parts]]
cid = 52120343
name = "一花依世界 鹿乃日文"
length = 292
resolution = "1920x1080"

[uploader]
uid = 316381099
name = "鹿乃ちゃん"

[snapshot]
snapshot-time = 1613320683.6551692
danmakus-count = 9060
likes-count = 59329
favorites-count = 56752
snapshot-by = "moe.lty.bgetlib/1.x"
