create-time = 1497425507
publish-time = 1441258612
avid = 2854383
bvid = "BV1us411U7SZ"
title = "【染音若蔡】昆西昆之恋"
category = "翻唱"
desc-base64 = "6Ieq5Yi2IA0KLy/mnIjlhYnmtbfpmIHnrZbliJLlkozpppblj5HnmoTokIzmm7LmmIbopb/mmIbkuYvmgYvjgJDljp/mm7LvvJrliJ3mgYvvvIHmsLTpm7fmiJjpmJ/vvIHjgJENCi8v562W5YiS77ya5aSc5pyI5r6E5YWJDQovL+Whq+ivje+8muWknOaciOa+hOWFie+8iOaciOWFiea1t+mYgeWumOWNmuWcsOWdgO+8mmh0dHA6Ly93d3cud2VpYm8uY29tL3UvNTY0MzUzNzMxNz90b3BuYXY9MSZhbXA7d3ZyPTYmYW1wO3RvcHN1Zz0x77yJDQovL+atjOaJi++8muafk+mfs+iLpeiUoe+8iDVzaW5n5Li76aG177yaaHR0cDovLzVzaW5nLmt1Z291LmNvbS9zb25ld2FrYW5hL2RlZmF1bHQuaHRtbO+8iQ0KLy/nlLvluIjvvJrolrDooaPojYnvvIhQ56uZSUTvvJo0OTU5MzA177yJDQovL+inhumike+8mumBl+mtgg0KLy/mhJ/osKLnnJ/lkI3kurLlpojnmoTpg6jliIblm77mjojmnYMNCi8v"
[[parts]]
cid = 4459868
name = ""
length = 248
resolution = "640x360"

[uploader]
uid = 1320347
name = "遗魂儿"

[snapshot]
snapshot-time = 1613320695.9577155
danmakus-count = 6946
likes-count = 12594
favorites-count = 1184
snapshot-by = "moe.lty.bgetlib/1.x"
