create-time = 1497424420
publish-time = 1353124319
avid = 395638
bvid = "BV11x411F77J"
title = " 蠢蠢的死法 Dumb Ways to Die 萌爆你（字幕）"
category = "综合"
desc-base64 = "5LyY6YW3IOaWsOa1qiDmvrPlpKfliKnkuprloqjlsJTmnKznmoRNZXRybyBUcmFpbnPliLbkvZzkuobov5nkuIDmrrXokIzokIzlhaznm4rlub/lkYrvvIzlnKjliJfkuL7kuobkuIDlpKfloIbooKLooKLnmoTmrbvms5XkuYvlkI7vvIzmj5DphpLlpKflrrbvvJrmsqHmnInmr5TlnKjngavovablkajlm7TkuI3ms6jmhI/lronlhajmm7TooKLnmoTkuovkuobvvIE="
[[parts]]
cid = 606961
name = ""
length = 181
resolution = "514x288"

[uploader]
uid = 535255
name = "看花满眼泪"

[snapshot]
snapshot-time = 1613320694.8454654
danmakus-count = 162
likes-count = 592
favorites-count = 252
snapshot-by = "moe.lty.bgetlib/1.x"
