create-time = 1497407337
publish-time = 1362856137
avid = 498593
bvid = "BV1jx411c7Qm"
title = "【MAD】Rewrite - 静流 - 恋文 - 1080p"
category = "MAD·AMV"
desc-base64 = "6Ieq5Yi2IDLlpKnml7bpl7TlgZrlh7rmnaXnmoRSZXdyaXRl6Z2Z5rWB55qETUFE44CC5Lul44CK5oGL5paH44CL5Li6QkdN77yM5ri45oiP5Lit55qEQ0fkuLrntKDmnZDvvIzop4bpopHpg6jliIblrozlhajmmK/liKnnlKhBdmlzeW50aOWBmjE2Yml05aSE55CG5pCe5Ye65p2l55qE5Lic6KW/77yI6JuL56KO5LqG5LiA5ZywVF9U77yJ77yM54S25ZCO55SoQVNT5YGa5LqG5a2X5bmV6YWN5LiK5Y6744CC6KeG6aKR5LiL6L296ZO+5o6l6KeB6K+E6K6644CC"
[[parts]]
cid = 830494
name = ""
length = 389
resolution = "640x360"

[uploader]
uid = 244111
name = "mawen1250"

[snapshot]
snapshot-time = 1613320690.8948967
danmakus-count = 485
likes-count = 979
favorites-count = 266
snapshot-by = "moe.lty.bgetlib/1.x"
