create-time = 1497427972
publish-time = 1470318765
avid = 5651775
bvid = "BV1rs411C7am"
title = " 【精灵宝可梦XY&Z】 皮卡丘之歌-大谷育江（ED）【中字】"
category = "音乐综合"
desc-base64 = "44CQ57K+54G15a6d5Y+v5qKmWFkmYW1wO1rjgJHjgJDkuK3lrZfjgJEg55qu5Y2h5LiY5LmL5q2MLeWkp+iwt+iCsuaxn++8iEVE77yJCk1QM+agvOW8j++8mmh0dHA6Ly9wYW4uYmFpZHUuY29tL3MvMXBLUUtsRU4KZmxhY++8iOaXoOaNn++8ieagvOW8j++8mmh0dHA6Ly9wYW4uYmFpZHUuY29tL3MvMWtWampmUmgK"
[[parts]]
cid = 9178140
name = ""
length = 80
resolution = "636x360"

[uploader]
uid = 3655738
name = "Nonman"

[snapshot]
snapshot-time = 1613320687.161043
danmakus-count = 1861
likes-count = 12947
favorites-count = 494
snapshot-by = "moe.lty.bgetlib/1.x"
