create-time = 1605715910
publish-time = 1605758416
avid = 500314100
bvid = "BV1gK411V7J7"
title = "【生日作】收下吧！全都是对你的感谢~！爱言叶III翻唱！"
category = "翻唱"
desc-base64 = "5oiR55+l6YGT6Z+z5LmQ5oqV56i/54K55Ye76YeP5LiN5Lya5aSq6auYCuS9huaYr+S9oOS7rOavj+S4gOadoeivhOiuuuOAgeavj+S4gOadoeW8ueW5le+8jOmDveaYr+aIkeeahOePjeWunQrov5nmmK/miJHnmoTmhJ/mg4XvvIzkuZ/or7fmiorkvaDku6znmoTmhJ/mg4XkvKDovr7nu5nmiJHlkKfvvIEK5biM5pyb5Lul5ZCO5q+P5Liq55Sf5pel77yM6YO95pyJ5L2g5Lus55qE6Zmq5Ly04p2kCuivjeabsu+8mkRFQ08qMjcK57yW5puy77yaUm9ja3dlbGwK5re36Z+z77ya6aWt5Zuj5a2QCuabsue7mO+8muS6kem6nyDmmZPnu68KUFbvvJrmspDoma4KLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQrilqAg6Ieq5oiR5LuL57uN6KeG6aKRIGF2Njk2MzgyMTcK4pagIOelreWTgeaZmuWuiee+pO+8mjEwNDA1NTM4NTIg56aB6KiAUemZkOe+pO+8mjczMTU3MTc5NiDov5vnvqTmr4/lpKnpg73mnInmmZrlronlkKzlk6bvvIEK4pagIOe9keaYk+S6keWSjOW+ruWNmu+8mumtlOeOi+mFsU1hb3VfT2ZmaWNpYWwK4pagIOaPkOmXrueuse+8mmh0dHA6Ly9wb3BpYXNrLmNuLyMvbWluZS9taW5lUXVpei8yNDU3OTMK4pagIOW9leaSree7hOi0puWPt++8mkBNYW916YWx56Wt5ZOB5Lil6YCJ6Ym06LWP5LyaCuKWoCDlvZXmkq3nu4TlrqHmoLjnvqTvvJo4ODUzNzI2OTgg6ZW/5pyf5oub5paw5Lit77yM5aSa6YeN56aP5Yip562J5L2g5ou/fu+8gQrilqAg5LqM5qyh5Yib5L2c6K+35Yqh5b+FQuermUDprZTnjovphbFNYW91X09mZmljaWFs5ZOm77yBdGFn77yaI+mtlOeOi+mFsSMj6a2U54mp57KuIwotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCuaIkeaYr+iZmuaLn3Vw5Li76a2U546L6YWxfuaYr+S7peWUseatjOmFjemfs+eOqea4uOaIj+S4uuS4u+eahOinhumikeWKv+a3t+ayjOezu+WPuOacuuWTpu+8gQrmr4/lkajpg73kvJrmm7TmlrDop4bpopF+5q+P5ZGo6ZqP57yY55u05pKt77yI5pma5LiKNy0xMOeCueW3puWPs++8iQrluIzmnJvlpKflrrbog73mnaXnnIt+5LiN5p2l5LuK5pma5bCx5p2l5ouc6K6/5L2g5ZOmfu+8gQ=="
[[parts]]
cid = 257260607
name = "爱言叶III3"
length = 249
resolution = "1920x1080"

[uploader]
uid = 163917943
name = "魔王酱Maou_Official"

[snapshot]
snapshot-time = 1613320684.462906
danmakus-count = 113
likes-count = 1395
favorites-count = 3580
snapshot-by = "moe.lty.bgetlib/1.x"
