create-time = 1580898938
publish-time = 1580898938
avid = 86921460
bvid = "BV1J7411H7tV"
title = "【中国铁路】京南一曲——致CRH系列永远的350kph（cover：起风了）"
category = "科学科普"
desc-base64 = "6KeG6aKR57Sg5p2Q5p2l6Ieq572R57uc77yM5oSf6LCi5ouN5pGE57Sg5p2Q55qE572R5Y+L44CB6K6w6ICF5ZKM5pGE5b2x5biI77yBCui/memmluatjOWOn+acrOaYr+aDs+WGmee7mUNSSDJD5ZKMM0PnmoTvvIzov5nkuKTkvY3ov4fljrvkuZ/mmK8zNTBrcGjov5DokKXnmoTlhYjpqbHvvIzogIzkuJTlhbPkuo5DUkgzODDvvIzmiJHlt7Lnu4/lhpnov4fkuIDpppbmrYzjgILnrYnliLDmnIDlkI7mrYzor43lhpnkuIvmnaXkuobvvIzlj5HnjrDlr7nkuo5DUkgzODDns7vliJfovablnovlkozpg6jliIbpq5jpk4Hnur/ot6/kuZ/pgILnlKjvvIzpgqPlsLHkuIDlubbliqDov5vljrvkuobjgIIK5omA6LCT55Sf5LiN6YCi5pe244CB5oCA5omN5LiN6YGH77yM5LiN6IO95pu05Yqg6YCC55So5LqOMkPjgIEzQ+WSjDM4MOezu+WIl+S6huOAguWItuS9nOi/meS4quinhumikeaYr+W4jOacm+iuqeabtOWkmuS6uu+8iOS4jeS7heaYr+eBq+i9pui/t++8ieefpemBk++8jOi/kOiQpemAn+W6pjM1MGtwaOeahOS4reWbveWKqOi9pue7hO+8jOS4jeS7heS7heacieKAnOWkjeWFtOWPt+KAneOAggrnpZ3npo/kuK3lm73pk4Hot6/jgII="
[[parts]]
cid = 148536032
name = "OUT_20200205_160509"
length = 311
resolution = "1280x720"

[uploader]
uid = 88164731
name = "A300B1"

[snapshot]
snapshot-time = 1614840409.83986
danmakus-count = 142
likes-count = 427
favorites-count = 544
snapshot-by = "moe.lty.bgetlib/1.x"
