create-time = 1497430378
publish-time = 1492332098
avid = 9885113
bvid = "BV15x411D7FQ"
title = "【1080P】Scarborough Fair《末日时在做什么？有没有空？可以来拯救吗？》第一话插曲"
category = "音乐综合"
desc-base64 = "5p6B5b2x5a2X5bmV56S+IOOAiuacq+aXpeaXtuWcqOWBmuS7gOS5iO+8n+acieayoeacieepuu+8n+WPr+S7peadpeaLr+aVkeWQl++8n+OAi+esrOS4gOivneS4reeahOaPkuabsu+8mlNjYXJib3JvdWdoIEZhaXLvvIznibnmhI/ljovkuobvvIzkuI3nn6XnqL/ku7blh7rmnaXlkI7ov5jmmK/kuI3mmK8xMDgwLi4u"
[[parts]]
cid = 16342574
name = "[JyFanSub][sukasuka-anime][01][GB][1080p]_clip~1"
length = 148
resolution = "640x360"

[uploader]
uid = 7880875
name = "星满星"

[snapshot]
snapshot-time = 1613320685.3210733
danmakus-count = 22
likes-count = 245
favorites-count = 54
snapshot-by = "moe.lty.bgetlib/1.x"
