avid = 16075983
bvid = "BV14x411j7q9"
title = "【原创】初音未来 V4C 中文版《告白》（《初梦》专辑收录曲目）【初音ミク】"
category = "VOCALOID·UTAU"
create-time = 1509984011
publish-time = 1509984011
desc-base64 = "5Yid6Z+z5pyq5p2l5a6Y5pa55o6I5p2D5q2j54mI5Lit5paH5LiT6L6R44CK5Yid5qKm44CL5pS25b2V5puyCgrnvZHmmJPkupHpn7PkuZDkuJPovpHotK3kubDlnLDlnYDvvJpodHRwOi8vbXVzaWMuMTYzLmNvbS9zdG9yZS9uZXdhbGJ1bS9kZXRhaWw/aWQ9MzY2ODEwOTUKCuOAiuWIneaipuOAi+aYr+eUsSBNaWthaSBNdXNpYyDliLbkvZzlubblj5HooYznmoTliJ3pn7PmnKrmnaXkuK3mlofpn7PkuZDkuJPovpHvvIzpm4blkIjkuobkvJflpJrnn6XlkI0gUCDkuLvnmoTmlrDkvZzvvIzlubbnlLHkvJflpJrlm73lhoXkuIDnur/kuJPkuJrpn7PkuZDliLbkvZzkurrlkozml6XmnKzpn7PkuZDliLbkvZzkurrnsr7lv4PmiZPno6jjgILov5nlvKDkuJPovpHkuZ/mmK/ojrflvpfkuobml6XmnKwgQ3J5cHRvbiDlrpjmlrnjgIHlm73lhoXniYjmnYPmlrnmlrDliJvljY7lkozml5fkuIsgUE9QUFJPIOWumOaWueaKleeov+ermeaOiOadg+eahOWInemfs+acquadpeato+eJiOS4k+i+ke+8gQoK5puy57uY5ZKM5bCB6Z2i5o+S55S75LiL6L2977yaaHR0cDovL3d3dy5taWthaW11c2ljLmNvbS9jb25mZXNzLmh0bWwKCuWRiueZvSBCR03kvLTlpY/kuIvovb3vvJoKbXAz77yaaHR0cDovL3QuY24vUmxuVjBhVAp3YXbvvJpodHRwOi8vZmlsZXMubWlrYWltdXNpYy5jb20vbXVzaWMvQ29uZmVzcyhJbnN0cnVtZW50YWxfVW5tYXN0ZXJlZCkud2F2LnppcAoK5ZGK55m9VmVyLkIgQkdN5Ly05aWP5LiL6L2977yaCndhdu+8mmh0dHA6Ly9maWxlcy5taWthaW11c2ljLmNvbS9tdXNpYy9Db25mZXNzLVZlci5CKEluc3RydW1lbnRhbF9Vbm1hc3RlcmVkKS53YXYuemlwCgrliLbkvZzkurrvvJpNdXNpa00gLyBtdXNpWGJveQrkvZzmm7LvvJpTaXJlbgrkvZzor43vvJpTaXJlbgrosIPmlZnvvJpTaXJlbiAvIERpZ2dlcgrmvJTllLHvvJrliJ3pn7PmnKrmnaUgVjRDCue8luabsu+8mueSkOWEv+eItwrmt7fpn7PvvJrpn6bmlazmsJEK5q+N5bim77ya6Z+m5pWs5rCRCuWwgemdou+8muiKseiQneS4jeaYr+iKseieugpQViDop4bpopHvvJrlnY/mjonljJbjga7pu5HlsqnvvIhBbGljZSDmmKDnlLvvvIkK5puy57uY77ya5rSb5bCP6aOe77yIQWxpY2Ug5pig55S777yJCgrmrYzor43vvJoKCuWPiOWIsOi/meS4gOWkqSDnhp/mgonnmoTlnLDmlrkK6aKk5oqW55qE5oyH5bCWIOaLqOWTjeS6huWQieS7lgrlrrPmgJXooqvpgZflv5gg5omN5LiA55u05q2M5ZSxCuebtOWIsOaIkeS7rOmDveWTvOedgCDpgqPlkYrnmb3nmoTmrYwKCuWkqeaYjuS5i+WJjSDpmarmiJHljrvpk7bmsrMK5bCG5aSp5LiK5pif5pifIOivleedgOaRmOS4i+WHoOmilwrnibXotbflj4zmiYsg5pS+5Zyo5LqG6IO45Y+jCueLrOWNoOa4qeaflAoK5oOz5Y676KeB5L2gIOaDs+WbnuWIsOmCoyDpgZflpLHnmoTov4fljrsK5oOz5Y676KeB5L2gIOaDs+i/t+WkseWcqCDnuYHmmJ/nmoTmlYXlsYUK5oOz5Y676KeB5L2gIOaDs+WGjeS4gOasoSDllLHmiJHku6znmoTmrYwgCgrlsLHnrpflpKflo7Dlkbzlloog5Lmf5Lyg6L6+5LiN5YiwCuS4jeefpeWQjeeahOS9juivrSDlnKjohJHkuK3njq/nu5UKCuWPiOWIsOi/meS4gOWkqSDnhp/mgonnmoTlnLDmlrkK6aKk5oqW55qE5oyH5bCWIOaLqOWTjeS6huWQieS7lgoK5oOz5Y676KeB5L2gIOaDs+WbnuWIsOmCoyDpgZflpLHnmoTov4fljrsK5oOz5Y676KeB5L2gIOaDs+i/t+WkseWcqCDnuYHmmJ/nmoTmlYXlsYUK5oOz5Y676KeB5L2gIOaDs+WGjeS4gOasoSDllLHmiJHku6znmoTmrYw="
[[parts]]
cid = 26258501
name = ""
length = 212
resolution = "640x360"

[upper]
uid = 82376847
name = "MikaiMusic未开封音乐"

[snapshot]
snapshot-by = "bget-fav-vocaloid-toml/inforeg.py/2.0"
snapshot-at = 1610110849.2920358
plays = 87610
danmakus = 1362
likes = 2930
favorites = 7938
coins = 5260
comments = 600
