create-time = 1497395460
publish-time = 1422636318
avid = 1941977
bvid = "BV1Jx411A7Ws"
title = "【白化洛天依】《天朝从众效应》PV付，信息量大，暂停党稳住三观！BY:绛舞乱丸"
category = "VOCALOID·UTAU"
desc-base64 = "6Ieq5Yi2IE1QM+ivleWQrOWcsOWdgO+8mmh0dHA6Ly95LmJhaWR1LmNvbS9qaW1teWwuDQpQVuS4i+i9veWcsOWdgO+8mmh0dHA6Ly9wYW4uYmFpZHUuY29tL3MvMWVRZVY2d3kNCuS4gOWmguaXouW+gOWOn+WIm+absu+8jOivtOeahOWwseaYr+aIkeS7rOavj+WkqemdouWvueeahOS7juS8l+S4lueVjOOAgjIwMTXkuIDlvIDlubTlpKfnrrToqIDvvJrlvZPkvaDlhbflpIfkuoboqIDooYzoh6rnlLHnmoTmnaHku7bkuI7lubPlj7Dml7bvvIzkvaDmm7TlhbflpIfnnYDkuIDku73ni6znq4vmgJ3ogIPmmI7ovqjmmK/pnZ7nmoTotKPku7vvvIzlm6DmraTvvIzor7fkuI3opoHorqnku47kvJfmlYjlupToh7Tkvb/kvaDnmoToqIDooYzovpzotJ/kuobkvaDnmoTotKPku7vjgILljovliLbvvJrmsLTml6DmnIjovanjgILor43jgIHmm7LjgIHmt7fjgIHosIPjgIFQVuOAgeWQjuacn++8mue7m+iInuS5seS4uA=="
[[parts]]
cid = 3000795
name = ""
length = 316
resolution = "640x360"

[uploader]
uid = 188951
name = "绛舞乱丸"

[snapshot]
snapshot-time = 1614839993.5642135
danmakus-count = 11548
likes-count = 25823
favorites-count = 3565
snapshot-by = "moe.lty.bgetlib/1.x"
