create-time = 1516617395
publish-time = 1516617394
avid = 18603489
bvid = "BV15W411i7cY"
title = "【洛天依V4翻唱】飞得更高【动点p】"
category = "VOCALOID·UTAU"
desc-base64 = "5Y6f5ZSxL+absi/or43vvJrmsarls7AK6LCD5pWZ77ya6YSZ5Lq6ClBW77ya5L2g54ycCua3t+mfs++8muS6uuW9ouWFjgoK57uI5LqO5pyJ5pe26Ze055So5aSp5L6dVjTmraPnu4/osIPkuIDpppbmm7LlrZDkuobvvIEK5Zug5Li65oCl552A5oOz5oqV56i/5omA5Lul55u05o6l55SoVjTnmoTlronoo4Xlm77ns4rkuobkuKpQVu+8ge+8iOiHquW3semDveaEn+inieWlveaHkk9yegrmhJ/osKLlhZTlhZTnmoTmt7fpn7PvvIzpobrluKblv4PnlrzkuIDkuIvmiJHku6zkv6nnmoTogp0uLi4uLgrlpb3kuoblup/or53kuI3lpJror7TvvIzor7flkKzvvIE="
[[parts]]
cid = 30349929
name = "洛天依V4中文版安装包用图"
length = 284
resolution = "1336x720"

[uploader]
uid = 12481783
name = "动次打次的动点p"

[snapshot]
snapshot-time = 1614840905.7014976
danmakus-count = 5094
likes-count = 11420
favorites-count = 7345
snapshot-by = "moe.lty.bgetlib/1.x"
