create-time = 1613064246
publish-time = 1613064246
avid = 246740089
bvid = "BV12v411a7kG"
title = "万分之一的光（洛天依）-纯钢琴版"
category = "VOCALOID·UTAU"
desc-base64 = "6Ieq5Yi26ZKi55C05pS557yW77yB5a6M5YWo6ICz5omS77yM5biM5pyb5L2g5Zac5qyi77yM5LmQ6LCx5Y+v6IO95LiN5piv5LiA5Lya55qE5LqL77yM6KaB562J5LiA562J44CCCgrljp/mm7Lkv6Hmga/lpoLkuIvvvJoK6Z+z5LmQ77yaQ2hpbGlDaGlsbArotJ3mlq/vvJrlsbHlj6PpgLLkuZ8K6byT5omL77ya5Y+j5Y+j5Y+j5Y+j5Y+jCuiwg+agoe+8muWKqOeCuVAK5bym5LmQ57yW6YWN77ya6IOh6Z2Z5oiQIC8gQ2hpbGlDaGlsbArlsI/mj5DnkLTvvJrlup7pmJQgLyDlvKDmtakK5Lit5o+Q55C077ya5q+V6IqzCuWkp+aPkOeQtO+8mumDjuiOuQrnm5HliLbvvJrkurrlvaLlhY4K5Ye65ZOB77yaVnNpbmdlcgpCVjFUcDR5MVM3Y3U="
[[parts]]
cid = 296549325
name = "万分之一的光"
length = 277
resolution = "1920x1080"

[uploader]
uid = 393436498
name = "Finally302"

[snapshot]
snapshot-time = 1613319866.8262868
danmakus-count = 1
likes-count = 88
favorites-count = 127
snapshot-by = "moe.lty.bgetlib/1.x"
