create-time = 1612437190
publish-time = 1612922712
avid = 246579769
bvid = "BV1Sv411e77F"
title = "【心华原创曲】浴火燃尽心上花【虚律vandu社】"
category = "VOCALOID·UTAU"
desc-base64 = "562W6K+NcHY65b2x56m6CuS9nOabsjrkuLTkuIAK57yW5puyOuaYn+WHmwrosIPmt7c65p6r57OWCuabsue7mDrokL3lm60K576O5belOumYv+emuwrlv4PljY7ljY7nlJ/ml6Xlv6vkuZDpuK3vvIHvvIE="
[[parts]]
cid = 292652619
name = "浴火燃尽心上花"
length = 187
resolution = "1920x1080"

[[staff]]
favorite-time = 12450
uid = 383758069
title = "UP主"
name = "虚律vandu社"

[[staff]]
favorite-time = 12450
uid = 436920836
title = "作词"
name = "Paradise_影空"

[[staff]]
favorite-time = 12450
uid = 323713810
title = "作曲"
name = "_临一"

[[staff]]
favorite-time = 12450
uid = 37774452
title = "编曲"
name = "星凛_Allein"

[[staff]]
favorite-time = 12450
uid = 53465668
title = "调校"
name = "枫糖烧仙草"

[[staff]]
favorite-time = 12450
uid = 384106103
title = "后期"
name = "唤阿离"

[uploader]
uid = 383758069
name = "虚律vandu社"

[snapshot]
snapshot-time = 1613319903.518539
danmakus-count = 0
likes-count = 182
favorites-count = 263
snapshot-by = "moe.lty.bgetlib/1.x"
