create-time = 1529644382
publish-time = 1529644382
avid = 25365533
bvid = "BV1xs41177rg"
title = "【相声】一日城管（洛天依×言和）"
category = "VOCALOID·UTAU"
desc-base64 = "55u45aOw44CK5LiA5pel5Z+O566h44CL44CQ5Y6f5Yib44CRCuS6uuiuvu+8mkDok67moLlQCuiDjOaZr++8mkDlpKfmoLnolYkK5Ymn5pysJuiwg+aVme+8mkBNb2t1cmVp5pyo54G15ZCbCuWJjeS9nO+8muOAiuiuuuiMtuOAi2F2MTk4MDgxODkKCuacgOi/keW/meedgOWKnueQhuavleS4mueahOaJi+e7re+8jOWGjeWKoOS4iuW8gOWktOWPiOa3u+S6huWkp+amgjEwMDDlpJrlrZfnmoTlhoXlrrnvvIzmiYDku6XmipXnqL/mr5TpooTmnJ/nmoTov5/kuobkuIDkupvvvIzov5jor7flkITkvY3op4LkvJflpJrmi4XlvoXjgIIK5pys5L2c5ZOB55qEU3RhZmblkozjgIrlpKfor53mmJ/lsJjjgIvnmoTlrozlhajkuIDoh7TvvIzmnKzmrKHnmoTkurrnianlkozog4zmma/kuZ/nu5jliLblvpfljYHliIblh7roibLvvIEK5YW25a6e6L+Z6YOo5L2c5ZOB5piv5LiA56+H5oqr552A5Li75rWB55u45aOw5aSW6KGj55qE5Lyg57uf55u45aOw77yM5byA5Zy65bm25LiN55u05o6l6L+b5YWl5Li76aKY77yM6KGo546w5b2i5byP5Lmf5LiN5piv5YWJ6Z2g5ZaK5Y+j5Y+35ZKM6KGo5Yaz5b+D77yM5LiN6L+H5Lmf5aSa5bCR5bim54K55oqV5py655qE5YaF5a6577yM5biM5pyb5aSn5a626IO95aSf55CG5oCn55yL5b6F77yM5LiA56yR6ICM6L+H44CCCuaIkeiHquW3seWvuei/memDqOS9nOWTgeeahOS6rOiFlOi/mOaYr+WNgeWIhuiHquS/oeeahO+8jOW4jOacm+S5n+iDveW+l+WIsOaCqOeahOiupOWPr++8jOaEn+iwouaCqOWvuei/memDqOS9nOWTgeeahOaUr+aMge+8gQoK5pyo54G15ZCb5LqOMjAxOOW5tDbmnIgyMuaXpQ=="
[[parts]]
cid = 50570768
name = "一日城管·终稿"
length = 506
resolution = "1280x720"

[uploader]
uid = 3220126
name = "Mokurei·木灵君"

[snapshot]
snapshot-time = 1614840810.8495355
danmakus-count = 1841
likes-count = 5673
favorites-count = 6101
snapshot-by = "moe.lty.bgetlib/1.x"
