create-time = 1497423941
publish-time = 1453867739
avid = 3676203
bvid = "BV1ps411X7QG"
title = "【洛天依×乐正绫原创】灼之花【PV付/COP】"
category = "VOCALOID·UTAU"
desc-base64 = "6Ieq5Yi2IOOAkOivjS/mm7LvvJpDT1AgIOe7mC/op4bpopHvvJpoaXNh6ZWcQOW5u+aciOmfs+S5kOWboiAgZXh0cmVtZWx5IHRoYW5rc++8muegluWOgua1quS6uuOAkQ0K44CQ6Z+z6aKR5LiL6L295Zyw5Z2A77yaaHR0cDovLzVzaW5nLmt1Z291LmNvbS95Yy8yODg5MjYxLmh0bWzjgJENCuOAkOezu+WIl+absuOAiueBsOeDrOOAi++8mmF2MzI4MzMwNeOAkQ0K44CQ5Lq65aOw5pys5a6277yaS0ImYW1wO+WTpua8j++8mmF2MzY3NjI2OOOAkQ0K"
[[parts]]
cid = 5884394
name = ""
length = 249
resolution = "640x360"

[uploader]
uid = 396194
name = "COPY"

[snapshot]
snapshot-time = 1614840018.4281557
danmakus-count = 8592
likes-count = 31380
favorites-count = 7085
snapshot-by = "moe.lty.bgetlib/1.x"
