create-time = 1611911112
publish-time = 1611911111
avid = 331445948
bvid = "BV1xA411u7t2"
title = "【墨清弦、洛天依】《秦淮河边的陈年往事》"
category = "VOCALOID·UTAU"
desc-base64 = "44CQ5aKo5riF5bym44CB5rSb5aSp5L6d44CR44CK56em5reu5rKz6L6555qE6ZmI5bm05b6A5LqL44CLY292ZXLpu4Tor5fmibbjgIIK5pys5a6277yaQlYxSno0eTFDN1U4CnB25pys5a6277yaQlYxOWI0MTE2N25nCua4o+iwg+a3t++8muacrFVQ44CC"
[[parts]]
cid = 289083035
name = "合成"
length = 233
resolution = "1920x1080"

[uploader]
uid = 319994112
name = "歪小姗"

[snapshot]
snapshot-time = 1612502760.958522
danmakus-count = 10
likes-count = 194
favorites-count = 332
snapshot-by = "moe.lty.bgetlib/1.x"
