create-time = 1611970851
publish-time = 1612015200
avid = 373977579
bvid = "BV1To4y1d7Sn"
title = "【初音未来原创曲】ACHROMATICITY【雨夜轻语】"
category = "VOCALOID·UTAU"
desc-base64 = "5L2c5ZOB57G75Z6L77ya5Y6f5Yib5puyCua8lOWUse+8muWInemfs+acquadpQror40v5puyL+iwgy/mt7cv5Yqo55S777ya6Zuo5aSc6L276K+tV2lzcHJhaW4KCuaEv+S9oOaIkeaJgOWcqOeahOWfjuW4guawuOi/nOWFhea7oeiJsuW9qeOAgg=="
[[parts]]
cid = 289737577
name = "S58_ACHROMATICITY"
length = 271
resolution = "1920x1080"

[uploader]
uid = 15512975
name = "雨夜轻语Wisprain"

[snapshot]
snapshot-time = 1612901933.6579814
danmakus-count = 17
likes-count = 383
favorites-count = 717
snapshot-by = "moe.lty.bgetlib/1.x"
