avid = 37061719
bvid = "BV13t411X7qS"
title = "【洛天依言和乐正绫墨清弦原创】塔之礼赞【αrtist5系列序曲】【管弦乐/史诗风】【霾AXIS】"
category = "VOCALOID·UTAU"
create-time = 1543551409
publish-time = 1543551409
desc-base64 = "5Y6f5Yib54mp6K+t6Z+z5LmQzrFydGlzdDXns7vliJfCt+W6j+absiDoh7TmiYDmnInliJvkvZzogIXvvIzngbXmhJ/kuI7nvo7nmoTkv6HlvpLjgILkurrlo7DmnKzlrrZhdjM3NTk5NDk1IArjgJDnrKzkuIDpobXvvJrml6Dph43lipvlsJHlpbNhdjM5MjY4MjI444CR44CQ56ys5LqM6aG177ya6LGh54mZ5aGU5bCR5aWzYXY0MjI0NzQ1NuOAkeOAkOesrOS4iemhte+8mueBsOatu+eXheWwkeWls2F2NDc2NTA1MTHjgJHjgJDnrKzlm5vpobXvvJrpu5HnvorlsJHlpbNhdjUzMDIwNjQw44CR44CQ56ys5LqU6aG177ya57qi55+z6JKc5bCR5aWzYXY3NzI5NjY2N+OAkQrmm7LvvJrkvp3muqrnpr4gfHwg562WL+ivje+8mumbqOeLuCB8fCDosIPvvJpNQUNIV09MRiB8fCDmt7fvvJrkvp3muqrnpr7jgIHmmJ/mmJ8gfHwg57uY77ya5rKi56m644CB5Zui5LiA44CBWUFMIHx8IOinhu+8mumlreS8iuWFuCB8fCDmqKHvvJrnoqfnqbrmrovkupEK5aOw5LmQ5ZCI5ZSx77ya546L5LiA6L+q77yI5ZCI5ZSx5oyH5a+877yJ44CB546L6ZKw55G2IHx8IOWQiOWUseWQjuWLpO+8muW8oOernuaWhyB8fCDlkIjllLHlvZXliLbvvJrllK/lkZzpn7PpopEgCuacrOWutuWwj+ivtOWcsOWdgO+8mmh0dHBzOi8vd3d3LmlxaW5nLmNvbS9ib29rLzcyMzYxCuS4i+i9veingeivhOiuuuWMuu+8jOaXoOWQiOWUseeJiOS8tOWlj+WwhuWcqOS6uuWjsOacrOWutuaKleeov+WQjuaUvuWHuu+8jOauv+WgguaXtuWwhuaUvuWHuuWQiOWUseeJiOS8tOWlj+OAggrlhajns7vliJdTVEFGRu+8mgrnrZbliJIv5L2c6K+N77ya6Zuo54u4CuS4lueVjOingu+8mumbqOeLuOOAgeayouepugrkurrorr7vvJrpm6jni7jjgIHmsqLnqbrjgIFOb3Jhc2ZlcgrkuZDluIjvvJrluIzmnJvntKLku7vlkIjotYRULUwtU+OAgeaYn+i+ieOAgeS+nea6quemvllpc2Vob+OAgeWwmOWao+WQjOWtpuOAgeW0qeWdj1NvdmlldHN5ClZD5pys5a6277ya5aKo5riF5bym44CB5rSb5aSp5L6d44CB6KiA5ZKM44CB5LmQ5q2j57urCuS6uuWjsOacrOWutu+8muWPjOesmQrosIPmoKHvvJpNQUNIV09MRuOAgU9RUQrnu5jluIjvvJrmsqLnqbrjgIFZQUzjgIHlm6LkuIDjgIHnu6vkuZ/ojLXjgIHlsI/ml6nlt53lsJjkuZ8KTG9nb+iuvuiuoe+8mlNvcGZpZQrlnLrmma/mkK3lu7rvvJrnoqfnqbrmrovkupEKUFbvvJrppa3kvIrlhbjjgIFydWth44CB552h54u444CBUGVsb2tpb+OAgeS4gOaKmOi1t+WUrgrnibnliKvmhJ/osKLvvJrpkqLouabjgIHllrXlkqrjgIHlkYbmr5vjgIFDa2tr"
[[parts]]
cid = 65123476
name = "1111111111(1)"
length = 234
resolution = "1920x1080"

[upper]
uid = 605473
name = "雨狸"

[snapshot]
snapshot-by = "bget-fav-vocaloid-toml/inforeg.py/2.0"
snapshot-at = 1610110861.1175425
plays = 444158
danmakus = 1736
likes = 21546
favorites = 26445
coins = 21025
comments = 3239
