create-time = 1610906884
publish-time = 1610942414
avid = 416182824
bvid = "BV1zV411t78c"
title = "【洛天依原创】《WA》【PV付】【FereNron_16】"
category = "VOCALOID·UTAU"
desc-base64 = "6Ieq5Yi2Cui/meaYr+S4gOmmlueci+S8vOasouS5kOWNtOaYr+iusui/sOiHquaIkeWli+aWl+eahOWmgumdkuibmeS4gOiIrOeahOS5kOWkqea0vueyvuelnueahOabsuWtkOOAguiZveeEtuebruiDveaJgOWPiueahOWkqeepuuWPquacieS6leWPo+mCo+S5iOWkp++8jOS9huS7luWNtOefpemBk+i/meS4lueVjOeahOWuveW5v+OAggrku5bllK/kuIDopoHlgZrnmoTkuovmg4Xkvr/mmK/igJTigJQK5LiA5b6A5peg5YmNCuivjeabsu+8mkFyeWFgQXJjeWFpaQrmm7Lnu5jvvJrojrnllrUK6LCD5pWZ77ya5aSp6JqV5YeJ5YeJ6LGGClBW77yaTlrmmKDnlLsK5ZWK77yM6L+Z6aaW5q2M57uI5LqO6IO95ZKM5aSn5a626KeB6Z2i5LqG44CC5piO5piO5LiA5Liq5aSa5pyI5YmN5bCx5Y+R5LqGUFbliqjmgIHnmoRvcnrjgIIK5aW95LqL5aSa56Oo77yM5biM5pyb5Y+v5Lul5Zac5qyi77yM6K6w5b6X5LiA6ZSu5LiJ6L+e5ZGQ44CCCuaMieeFp+aXtumXtOe6v+eahOWOhuWPsui/m+eoi+WPkeWxle+8jOaOpeS4i+adpeS8mui/m+WFpeWIsOS4gOS4quavlOi+g+mrmOS6p+eahOaXtuaute+8iOebuOWvue+8iW9yegrkvJrlnKjnvZHmmJPkupHlkIzmraXvvIzkuozmrKHliJvkvZznp4Hkv6HljbPlj6/vvIjomb3nhLblpKfmpoLnjoflj6/og73msqHmnInvvIzkvYbmmK/ov5jmmK/opoHlhpnlh7rmnaXvvIkK5q2M6K+N77yaCuWkqeepuuW+iOWwjyDkvYbkuJbnlYzljbTlvojlpKcK5aSp56m66YKj5LmI6auYIOS5n+W+ruS4jei2s+mBkwroh6rnlLHnmoTpuJ8g5oiR5LiN5oOz5Y675q+U6L6DCuWboOS4uuaIkeeahOW/g+S4reacieedgOebruaghwoK55uu5qCH5b6I5bCPIOS9huiInuWPsOWNtOW+iOWkpwrkuI3lgZznmoTlkJHliY0g6L+H56iL6Jm95peg6IGKCuS9huaIkeefpemBkyDov5nmmK/miJHnmoTmoqbmg7MK5Y+q6KaB5aWL5paX6L+HIOWTqueuoei/h+eoi+aXoOiBigoK5ZOH5ZOH5ZOH5ZOH5LiA5q2l5LiA5q2lIOaFouaFouaFouaFouWQkeWJjQrmiJHmiJHmiJHmiJHnnLznpZ7nrIPlrpog5Y+q5Li66YKj57yV5YWJCuWTh+WTh+WTh+WTh+S4gOatpeS4gOatpSDmhaLmhaLmhaLmhaLlkJHliY0K5ZOH5ZOH5ZOH5ZOH5ZOH5ZOH5ZOH5ZOHIOS4gOW+gOaXoOWJjQoK5ZOm5ZOH5ZOH5ZOH5ZOH5LiA5q2l5LiA5q2lIOaFouaFouaFouaFouWQkeWJjQrmiJHmiJHmiJHmiJHnnLznpZ7nrIPlrpog5Y+q5Li66YKj57yV5YWJCuWTh+WTh+WTh+WTh+S4gOatpeS4gOatpSDmhaLmhaLmhaLmhaLlkJHliY0K5ZOH5ZOH5ZOH5ZOH5ZOH5ZOH5ZOH5ZOHIOS4gOW+gOaXoOWJjQoK5LiA5b6A5peg5YmNCgrlk4flk4flk4flk4fkuIDmraXkuIDmraUg5oWi5oWi5oWi5oWi5ZCR5YmNCuaIkeaIkeaIkeaIkeecvOelnuesg+WumiDlj6rkuLrpgqPnvJXlhYkK5ZOH5ZOH5ZOH5ZOH5LiA5q2l5LiA5q2lIOaFouaFouaFouaFouWQkeWJjQrlk4flk4flk4flk4flk4flk4flk4flk4cg5LiA5b6A5peg5YmNCgrlk6blk4flk4flk4flk4fkuIDmraXkuIDmraUg5oWi5oWi5oWi5oWi5ZCR5YmNCuaIkeaIkeaIkeaIkeecvOelnuesg+WumiDlj6rkuLrpgqPnvJXlhYkK5ZOH5ZOH5ZOH5ZOH5LiA5q2l5LiA5q2lIOaFouaFouaFouaFouWQkeWJjQrlk4flk4flk4flk4flk4flk4flk4flk4cg5LiA5b6A5peg5YmNCgrkuIDlvoDml6DliY0KCuWkqeepuuW+iOWwjyDkvYbkuJbnlYzljbTlvojlpKcK5aSp56m66YKj5LmI6auYIOS5n+W+ruS4jei2s+mBkwroh6rnlLHnmoTpuJ8g5oiR5LiN5oOz5Y675q+U6L6DCuWboOS4uuaIkeeahOW/g+S4reacieedgOebruaghwoK55uu5qCH5b6I5bCPIOS9huiInuWPsOWNtOW+iOWkpwrkuI3lgZznmoTlkJHliY0g6L+H56iL6Jm95peg6IGKCuS9huaIkeefpemBkyDov5nmmK/miJHnmoTmoqbmg7MK5Y+q6KaB5aWL5paX6L+HIOWTqueuoei/h+eoi+WkmuaXoOiBig=="
[[parts]]
cid = 283877407
name = "wa3_1"
length = 228
resolution = "1920x1080"

[[staff]]
favorite-time = 12450
uid = 433219143
title = "UP主"
name = "Arya_Arcyaii"

[[staff]]
favorite-time = 12450
uid = 37059846
title = "调校"
name = "天天凉凉豆"

[uploader]
uid = 433219143
name = "Arya_Arcyaii"

[snapshot]
snapshot-time = 1612901907.2300792
danmakus-count = 13
likes-count = 262
favorites-count = 403
snapshot-by = "moe.lty.bgetlib/1.x"
