create-time = 1554428440
publish-time = 1554438650
avid = 48312083
bvid = "BV1ab411g7Fb"
title = "【心华原创】如见青山【忘川风华录】"
category = "VOCALOID·UTAU"
desc-base64 = "5oC7562W5YiS77ya5pyo5a6B5pyo6JKZCuS8geWIkui/kOiQpe+8muWhlOW6kwrnm5HliLbvvJrljb/pm4XjgIHlsI/ku5njgIHpob7pm6rmn5TjgIHml6DlsL3lpI8K5L2c5puy77ya5r2u5rGQLXRpZGUgfCDkvZzor43vvJrlhonor63kvJggfCDnvJbmm7LvvJrmgqDmgqDphbEK5ryU5ZSx77ya5b+D5Y2OIHwg6LCD5pWZ77ya6Iqx5YS/5LiN5ZOtIHwg5re36Z+z77yaTXIu5pu+57uPIHwg56yb5a2Q77ya5Zua54mbIHwg5oiP6IWU6Z+z5pWI77yaS0JTaGlueWEK6KeG6aKR77ya5q6L5Z6j55WZ5qKmJkZsaXk344CQ6bq76Jav5pig5YOP44CRfCDmm7Lnu5jvvJrnmb3phJTmnbEK5bCP5ZKM5bCa77yM6Iy256KX55WZ57uZ5L2g77yM562J5oiR5Lit5LqG6YeR56eR54q25YWD77yM5a6D5bCx5piv5L2g5Lus55qE6ZWH5a+65LmL5a6d5LqG77yM5ZOI5ZOI77yBCuWJjeS9nOWKqeaUu+OAkOellum+meWQn+OAkWF2NDIzNDg0NDfjgJDlv4PkuIrnp4vjgJFhdjM2NTgxODQ344CQ5qCW5Yew44CRYXYzNDE1ODMyN+OAkOewquiKseS6uumXtOOAkWF2MzIyMzY1NjHjgJDlsbHmsrPku6TjgJFhdjI5ODYxOTY444CQ5piT5rC06K+A44CRYXYyNzkyODQ0OSDjgJDmtJvpmLPmgIDjgJFhdjI2MjczOTM5IOOAkOWkmuaDheWyuOOAkWF2MjUzODYyMDc="
[[parts]]
cid = 109446771
name = "如见青山debug"
length = 206
resolution = "1920x1080"

[uploader]
uid = 326258472
name = "忘川风华录"

[snapshot]
snapshot-time = 1613319825.6407382
danmakus-count = 5233
likes-count = 55679
favorites-count = 66925
snapshot-by = "moe.lty.bgetlib/1.x"
