create-time = 1553430166
publish-time = 1553437841
avid = 47224641
bvid = "BV1tb411471K"
title = "《暖春将至》——诗人海子逝世30周年原创V家纪念曲（言和）*✲ﾟ*❁面朝大海，春暖花开❁*✲ﾟ*"
category = "VOCALOID·UTAU"
desc-base64 = "44CK5pqW5pil5bCG6Iez44CLc3RhZmYK6K+N5puy77ya5rW35qC8Cua3t+e8lu+8mua1t+m4nwrosIPmlZnvvJrkvIrmsLRfVXJ5YW4K5puy57uY77ya6Ieq5Yqo5YWJ5ZyICuW9seWDj++8mum7keiJsuWwj+eZveWFlO+8iOmjnuexs+aYoOeUu++8iQrnibnliKvmhJ/osKLvvJrpmYznhLYv57Gz5a6XL+Wuq+e+veWkqeS+nQrnrZbliJIv6KeG6KeJ6I2J5qGI77ya6LWkbGVvcGFyZArnm5HnnaPvvJror7ror7rlsI/nhornjKsKCgoj5rW35a2Q6YCd5LiWMzDlkajlubQj5b2T5Luj6K+X5Lq65rW35a2Q6YCd5LiW5LqOMTk4OeW5tDPmnIgyNuaXpe+8jOS7iuW5tOaYr+S7luemu+W8gOaIkeS7rOeahOesrDMw5bm044CC5LuW55qE6K+X5q2M5b2x5ZON5LqG5LiA5Luj5Y+I5LiA5Luj5Lq677yM6ICM5YW25Lit5pyA5pyJ5ZCN55qE44CK6Z2i5pyd5aSn5rW377yM5pil5pqW6Iqx5byA44CL55u05Yiw5LuK5aSp5Lmf5bm/5Li65Lyg6aKC5LqO5LiW5Lq65LmL6Ze044CC5Zyo6L+Z5Liq54m55q6K55qE5pel5a2Q77yM5oiR5Lus5YWx5ZCM5Yi25L2c5LqG57qq5b+16K+X5Lq65rW35a2Q55qE5LitVuWOn+WIm+absuOAiuaaluaYpeWwhuiHs+OAi++8jOWcqOatpOS4uuWkp+WutuW4puadpeelneemj+KAlOKAlOKAnOmZjOeUn+S6uu+8jOaIkeS5n+S4uuS9oOelneemj+OAguaEv+S9oOacieS4gOS4queBv+eDgueahOWJjeeoi++8jOaEv+S9oOacieaDheS6uue7iOaIkOect+Wxnu+8jOaEv+S9oOWcqOWwmOS4luiOt+W+l+W5uOemj+OAguaIkeWPquaEv+mdouacneWkp+a1t++8jOaYpeaaluiKseW8gOOAguKAnQ=="
[[parts]]
cid = 83300536
name = "《暖春将至》正式版（pv已做修正、调教与混音已优化）"
length = 281
resolution = "1920x1080"

[uploader]
uid = 3264161
name = "德育主任Heather"

[snapshot]
snapshot-time = 1614840794.3479314
danmakus-count = 912
likes-count = 15027
favorites-count = 13234
snapshot-by = "moe.lty.bgetlib/1.x"
