create-time = 1547259042
publish-time = 1547259041
avid = 40513142
bvid = "BV1gt411W79R"
title = "【徵羽摩柯、乐正龙牙原创曲】咱俩谁管谁叫爹【PV付 ft. Vsinger全员】"
category = "VOCALOID·UTAU"
desc-base64 = "5YmN6Zi15a2Q6Lef5pyL5Y+L546p5LqG5aW95Yeg5aSp6L+Z5Liq5ri45oiP77yM5q+P5qyh6YO96KKr5Z2R6L6T77yM54S25ZCO56qB54S25Y+R546w6L+Z5ri45oiP5pivN+aLjeWtkOS4gOWbnuWQiOeahO+8jOaEn+inieWGmeWHuuabsuWtkOeahOivneS8muW+iOWlveeOqe+8jOS6juaYr+WwseWGmeWHuuS6hui/meS5iOS4quaymembleabsuWtkOeEtuWQjuaLieS6huelnuacqOadpeWBmuS6hueBtemtglBW77yBCuS8tOWlj+WmguaenOaciemcgOimgeeahOivneWcqOi/memHjO+8iOS8muacieWQl++8n++8ie+8mmh0dHBzOi8vbXVzaWMuMTYzLmNvbS8jL2FsYnVtP2lkPTc1MTM4Nzg0CumZpOS6huS4pOS9jeeUt+Wjq+eahOS8pueQhuWNmuW8iOS5i+Wklu+8jOWQhOS9jeWPr+S7peWQrOWQrOWQjumdouWHoOS9jeWls+Wjq+eahOWNs+WFtOa8lOWlj++8iAoK5puy77ya5Yqo54K5cArnu5gvUFbvvJrnpZ7mnKgK546p55qE77ya5b6157695pGp5p+v77yM5LmQ5q2j6b6Z54mZCueci+eDremXueeahO+8mua0m+WkqeS+ne+8jOiogOWSjO+8jOS5kOato+e7q++8jOWiqOa4heW8pgoK5ri45oiP55qE546p5rOV5ZKM5aOw5piO6YO95Zyo6KeG6aKR5pyA5YmN6Z2i5LqG77yM5ZCE5L2N55yL5LiA5ZOI77yBCuWlveaDueivt+WQrO+8gQ=="
[[parts]]
cid = 71153469
name = "爸比01_bilibili_Mux"
length = 231
resolution = "1920x1080"

[uploader]
uid = 12481783
name = "动次打次的动点p"

[snapshot]
snapshot-time = 1614840863.09276
danmakus-count = 3922
likes-count = 49588
favorites-count = 49426
snapshot-by = "moe.lty.bgetlib/1.x"
