create-time = 1611030602
publish-time = 1611030601
avid = 458629091
bvid = "BV1y5411n75F"
title = "【诗岸】欢颜【诗岸2021诞生日】"
category = "VOCALOID·UTAU"
desc-base64 = "5bGx5bGx5a6d6LSd55Sf5pel5b+r5LmQfgrkvYbmmK/mnaXkuI3lj4rmlbTop4bpopHkuoblsLHmkJ7kuobkuKrkuIDlm77mtYEK5ZCs5q2M77yM6YeN54K55ZCs5q2MCgrmrYzmm7LvvJrmrKLpopwK5Y6f5ZSx77ya6b2Q6LGrCue/u+WUse+8muivl+WyuArosIPmoKHvvJrnkZ7lrolSeWFu5LiN6LeR6LCD"
[[parts]]
cid = 284205490
name = "【诗岸】欢颜【诗岸2021诞生日】"
length = 284
resolution = "1280x720"

[uploader]
uid = 108845996
name = "瑞安Ryan不跑调"

[snapshot]
snapshot-time = 1614839985.0614507
danmakus-count = 72
likes-count = 994
favorites-count = 1645
snapshot-by = "moe.lty.bgetlib/1.x"
