create-time = 1613072873
publish-time = 1613072873
avid = 416639539
bvid = "BV1nV411i7yE"
title = "【钢琴】不问天 2021拜年纪单品翻弹（附谱）"
category = "演奏"
desc-base64 = "5pys5a6277yaQlYxc3Y0eTFmN1EyCuacrOWutlN0YWZm77yaCuS8geWIku+8muW5s+WuieWknOeahOWZqeaipgrkvZzmm7LnvJbmm7LvvJpwYXBhd+azoeazoQrkvZzor43vvJpWYWdhcnkK5ryU5ZSx77ya6K+06K+0Cuesm+WtkO+8muWbmueJmwrmnKjlkInku5bvvJpwYXBhd+azoeazoQrmt7fpn7PvvJrkuJzlrZAK5pig5YOP5Yi25L2c77yaQWxpY2XmmKDnlLsK5YiG6ZWc6K6+6K6h77ya6bm/55CD55CDCue+juacr++8mum5v+eQg+eQg+OAgem7keWTpemXquS6ruOAgembqOS7pOOAgeahg+WkmuaxgeOAgeeTt+Wwj+mxvArljp/liqjnlLvvvJrpsbzogonljbfjgIFDaGlheWHjgIFPb3BzWEQK6KeG6aKR6K6+6K6h77yaRGdsZTMzNzAK5Y2P5Yqb77ya6Zu36Im+TGlnaHRBSOOAgeS4nOmTg+OAgeadgOadgOOAgUNra2sK4oCU4oCU4oCU4oCU4oCU4oCUCuadpeS6huadpeS6hu+8geazoeazoeS4iuaLnOW5tOelreeahOesrOS4ieW5tO+8jOS5n+aYr+aIkee/u+W8ueazoeazoeS9nOWTgeeahOesrOS4ieW5tO+8gQror7blmL/vvIzlpKflubTliJ3kuIDnv7vlvLnmi5zlubTnpa3pgJDmuJDmiJDkuLrkuaDmg6/kuobvvZ4K5LuK5bm055qE5L2c5ZOB5L6d54S25b6I5Yqo5ZCs5ZOm77yBCgpc5rOh5rOhL1zms6Hms6EvXOazoeazoS8KXFZhZ2FyeS9cVmFnYXJ5L1xWYWdhcnkvCgrkuZDosLHpk77mjqXvvJpodHRwczovL3Bhbi5iYWlkdS5jb20vcy8xQWE4Ukx0Z1N0eEhEQ2R5aVQ5R1pZUSAK5o+Q5Y+W56CB77yaYmlsaSAKCuWJjeS9nOaOqOiNkO+8mgoyMDE544CK57mB5Y2O5ZSx6YGN44CLQlYxRGI0MTFyN0VZCjIwMjDjgIrmqKrnq5bmkofngrnmipjjgItCVjFMNzQxMWs3ejEKKuOAiueZvuaIj+S6uumXtOOAi0JWMU1YNHkxNTdqVwoKU3BlY2lhbCBUaGFua3MKcGFwYXfms6Hms6E="
[[parts]]
cid = 296589135
name = "【钢琴】不问天 2021拜年祭单品翻弹"
length = 260
resolution = "1920x1080"

[uploader]
uid = 128548736
name = "逆卷一多"

[snapshot]
snapshot-time = 1613319839.7752163
danmakus-count = 12
likes-count = 143
favorites-count = 327
snapshot-by = "moe.lty.bgetlib/1.x"
