avid = 456845628
bvid = "BV1L5411h7cc"
title = "【洛天依原创曲】《感性细腻亦可撑起世界》—让天依官设\"敏感细腻\"飞！P主之歌【运佳BlackberryP】【原创PV付】"
category = "VOCALOID·UTAU"
create-time = 1597948234
publish-time = 1598076014
desc-base64 = "6YOo5YiG5YmN5L2c5o6o6I2Q77yI5pu05aSa5aW95ZCs55qE5Y6f5Yib6Z+z5LmQ6KeBQOi/kOS9s0JsYWNrYmVycnlQ55qE5Liq5Lq65Li76aG177yJ77yaCuOAkOacrOacn+S4u+aOqOOAkSBCVjFtdDQxMVk3R3Eg44CK5rW35bKb6K6h5YiS44CLIOWkqeS+nemYv+e7q+epv+avlOWfuuWwvO+8geWYv+WYv++8geKcp9mpKMuKz4nLiyop2YjinKcK44CQMXfliqnmlLvjgJEKQlYxOEo0MTFZN2N1IOOAiua0m+adieeftuW6puWBh+adkeeahOaipumcsuOAizF35pKt5pS+5Yqp5pS777yBdXDkuLvmnIDniLHmipXnqL/vvIHlkozph5Hlj5HlsJHlpbPnmoTmtarmvKvniLHmg4XmlYXkuovvvIHinKfZqSjLis+Jy4sqKdmI4pynCkJWMU1XNDExcTdGSyDjgIrnp4HkurrmuK/mub7jgIsgMXfmkq3mlL7liqnmlLvvvIHlrqvltI7pqo/liqjnlLvmj5Lmm7Lpo47moLwK44CQ5q6/5aCC5puy44CRQlYxczc0MTFCN3lvIOOAiuW5uOWtmOOAiyAK44CQMTB35Yqp5pS744CRCkJWMUJFNDExZzdiM+OAiuWkj+WkqeW/q+imgei/h+WOu+S6huOAiyLoh7TljrvkuJbnmoTnq6XlubTlpbPnjqnkvLQiCkJWMW14NDExbjdQVyDjgIrnlLXlvbHlsJHlpbPjgIsgM3fmkq3mlL7liqnmlLvvvIEg6L+e6LSv55qE5peL5b6LIOS4k+ayu+W8uui/q+eXhwpCVjFLNDQxMTk3Z1og44CK6LWM5Z+O44CL5L2g5Lya5oqK5aSp5L6d5bim6LWw5ZCX77yBCkJWMXo2NHkxVDdzdeOAiuS4gOW8gOWni+aIkeS7rOmDvemZjOeUn+OAiyDlpKnkvp3mg7PlkozkvaDlgZrmnIvlj4vlkJbvvIEK44CQ6L+c5pep44CRCkJWMVJzNDExVzc0V+OAilRvdWNoZWTjgIsgIuWRhuavm+eahOaWueWQkeWwseaYr+S9oOWdkOWcqOeahOWcsOaWuSIKQlYxSng0MTFrN1Nv44CK5pS/5a6X5ZCb55qE5aSN5LuHwrfkvKrjgIsKCuOAkHN0YWZm44CRCuabsi/or40v5ZKM5aOw57yW5YaZL+etluWIki/ph5HkuLvvvJrov5DkvbNCbGFja2JlcnJ5UArosIMv5re377ya5ZOI5aOr5aWHUArnvJbvvJpBLk0uUgrnu5jvvJpzdXlhClBW77ya55CJ55KD54yr5pig5YOPCnZvY2Fs77yaIEDmtJvlpKnkvp0KCuacrOS9nOWTgeeUsSLov5DkvbNCbGFja2JlcnJ5UCLkuKrkurrlh7rlk4HvvIjni6zlrrbotZ7liqnjgIHnrZbliJLvvIkKCumfs+S5kOeugOS7i++8mgrml4vlvovmlrnpnaLvvIzkuLvopoHmmK/kuLrlpKflrrblsZXnpLrkuIDkuKrmsqHnu5nlpKflrrblkKzov4fnmoTlhbfkvZPpo47moLzvvIzml4vlvovliqDlhaXkuoblj6Tlhbjpn7PkuZDlhYPntKDvvIzmlbTpppbmrYzjgIHljIXmi6zmrYzor43ov73msYLpn7PkuZDliafmm7Lnm67nmoTmhJ/op4njgILnvJbmm7LkuIrvvIzliqDlhaXkuobkuqTlk43kuZDjgIHnrqHlvKbkuZDlhYPntKDjgIIK5q2M6K+N566A5LuL77yaCuWcqOi/meS4quW/q+iKguWlj+eahOaXtuS7o+S4re+8jCLmhJ/mgKfnu4bohbsi5Lmf6K645LiN5piv5a6e55So55qE5oCn5qC877yM6L+Z56eN5oCn5qC85LiO5aSn5LyX5a6h576O5qC85qC85LiN5YWl44CCCuS9huWug+Wni+e7iOaYr+acgOe+jueahOaAp+agvOOAgumVv+i/nOadpeiusu+8jOWug+WGs+WumuS6huS4gOS4quS6uueahOagvOWxgOOAggrnlLfnlJ/kuI3kuIDlrpropoHnjqnnq57mioDkvZPogrLvvIznlKjoh6rlt7HnmoTmhJ/mgKfnu4bohbvljrvliJvkvZzvvIzkuZ/lj6/ku6XlvojigJzluIXmsJTigJ3jgIIK5Yib5L2c44CB5YaZ5q2M5LiN5piv5Li65LqG6ICN5biF77yM6L+Z6aaW5q2M5LiO5L2g5YiG5Lqr5oiR5Yib5L2c55qE5rip5p+U55CG55Sx44CCCumfs+S5kOaYr+eUn+WRve+8jOacieS6m+aDheWGteS4i++8jOW5tuS4jeaYr+epuuivne+8jOW5tuS4jeWkuOW8oOOAggoK6L+Z6aaW5q2M55qE5q2M6K+N77yM5piv5LuO5oiR5Liq5Lq655qE6KeS5bqm5Ye65Y+R55qE77yM5oiR55qE5oCn5qC85b6I6Zq+5oC757uT5b2S57qz77yM5L2G4oCc5oSf5oCn57uG6IW74oCd5piv5oiR5q+U6L6D5pyJ5Luj6KGo5oCn55qE5LiA5Liq5oCn5qC844CCCumZpOS6huKAnOWQg+i0p+KAneOAgeKAnOWPr+eIseKAne+8jOKAnOaVj+aEn+e7huiFuyLkuqbmmK/mtJvlpKnkvp3nmoTlrpjorr7vvIzorqnlroPpo57vvIEKCuWGmeatjOS4jeaYr+aIkeeahOiBjOS4mu+8jOaYr+aIkeS7juWwj+WIsOWkp+eahOeIseWlve+8jOaIkeeahOS9nOWTgeWdh+aYr+iHqui0ueOAgeWOn+WIm++8jOadpeiHqumfs+S5kOeahOS4gOS6m+Wwj+Wwj+aUtuWFpeS5n+WFqOmDveWbnummiOWIsOS6humfs+S5kOS4reOAggrmiJHmipXnqL/mnIDmoLnmnKznmoTnm67nmoTmmK/vvJrlhpnmiJHoh6rlt7Hmg7PlhpnnmoTmrYzvvIzliIbkuqvpn7PkuZDvvIzpgoLpgIUi5oeC5oiR55qE5ZCs5LyXIuOAggroi6Xog73pobrkvr/mlLbojrfpq5jmtYHph4/jgIHllYbkuJrmgKfvvIjph5HpkrHvvInvvIzlvZPnhLbkuZ/kuI3plJnvvIzkuZ/nrpfmmK/miJHnlKjniLHlj5HnlLXlvpfliLDkuobkuIDkupvlsI/lsI/nmoTlm57ppojigJTigJTkvYbov5nlubbkuI3mmK/lv4XopoHnmoTvvIzlgZrpn7PkuZDkuI3mmK/miJHnmoTnlJ/mtLvmnaXmupDlkozogYzkuJrvvIzmiYDku6XmiJHlnKjpn7PkuZDkuK3lvojoh6rnlLHjgIIK6Iul5oiR5Y+q6IO95YGa57qv57K56L+O5ZCI5ZCs5LyX55qE6Z+z5LmQ77yM5oiW5piv5oiR5Y+q5oOz6KaB6YeR6ZKx5ZKM5rWB6YeP77yM5oiW5piv5b2x5ZON5LqG5oiR55qE55Sf5rS74oCU4oCU44CQ6YKj5oiR5a6M5YWo5rKh5b+F6KaB5oqV56i/5Y6f5Yib6Z+z5LmQ44CR77yM5LiN5aaC5Zyo5oiR55qE5Li75Lia44CB5LiT5Lia5LiK57K+6L+b77yI6L+Z5a+55oiR5p2l6K+05piv5q2j5Lia77yM6Z+z5LmQ5omN5piv5LiN5Yqh5q2j5LiaMjMzM++8ie+8jOaIluaYr+aKleS4gOS6m+iQpemUgOexu+inhumikeOAggoK5Zyo6Z+z5LmQ5Lit77yM5oiR5LiN6ZyA6KaB5LiA5Lqb5Li76KeC55qE5bu66K6u77yM5YyF5ous6Ieq6K6k5a6i6KeC5a6e5YiZ5Li76KeC55qE5bu66K6u77yM5oiW5piv6LaF5Ye65oiR5Lia5L2Z5Yib5L2c5p2h5Lu255qE5LiA5Lqb5bu66K6u44CCCuOAkOWcqOS/neivgemfs+S5kOWfuuacrOWuouingui0qOmHj+OAgeWfuuacrOWQrOS8l+aEn+WPl+eahOWQjOaXtu+8jOaIkeS8muWcqOmfs+S5kOS4re+8jOWwveaDheWBmuiHquW3seOAguOAkQ=="
[[parts]]
cid = 226820992
name = "感性细腻亦可撑起世界-运佳"
length = 294
resolution = "1920x1080"

[[staff]]
uid = 5009841
title = "UP主"
name = "运佳BlackberryP"

[[staff]]
uid = 11218480
title = "曲绘"
name = "酥牙"

[[staff]]
uid = 529083
title = "调校"
name = "哈士奇P"

[[staff]]
uid = 281804983
title = "视频制作"
name = "琉璃猫映像"

[upper]
uid = 5009841
name = "运佳BlackberryP"

[snapshot]
snapshot-by = "bget-fav-vocaloid-toml/inforeg.py/2.0"
snapshot-at = 1610110867.7281454
plays = 33886
danmakus = 192
likes = 5068
favorites = 4574
coins = 3549
comments = 539
