create-time = 1610555624
publish-time = 1610555624
avid = 543727677
bvid = "BV1Kv4y1f7Xs"
title = "【墨清弦原创】星之祈愿2021 Adult Ver.【PV付】"
category = "VOCALOID·UTAU"
desc-base64 = "5LiA5bm05YmN55qE5puy5a2Q77yM6bi95LqG5LiA5bm05aSaDQrlgZrkuobkuIDkupvml6DlhbPnl5vnl5LnmoTmlLnliqjvvIzov5jmmK/kuIDlpoLml6LlvoDnmoTlubznqJoNCue9keaYk+S6keWPkeW4g+mtlOaUueaYn+WwmOeUtemfs++8jOe+juWQjeWFtuabsOaYn+epuue6quW/teeJiO+8jOS4uuS6hue6quW/teaYn+WwmOeahOaYn+S5i+eliOaEvw0KDQrlvZPml7blhpnnu5nmn5DkuKrlpbPlkIzlrabnmoTmrYxoaGgNCuWOu+W5tOeahOS7iuWkqeeahOWHoOWkqeS5i+WQju+8jOmdnuimgeWQteedgOaIkee7meWlueS4gOS7veeUn+aXpeekvOeJqQ0K5b2T5pe25rC05bmz5Lmf6Laz5aSf5L2O5LiL77yM6L+Z5qyh6YeN5paw5YaZ5LqG5Lu956iN5aW954K555qE5puy5a2QDQrov5nkuI3vvIzlpbnpqazkuIrlj4jopoHov4fnlJ/ml6XkuobigKY="
[[parts]]
cid = 282077360
name = "墨清弦Adult"
length = 246
resolution = "1440x1080"

[uploader]
uid = 283373814
name = "UNDERFiNED千羽凌云"

[snapshot]
snapshot-time = 1612502770.3736567
danmakus-count = 7
likes-count = 143
favorites-count = 161
snapshot-by = "moe.lty.bgetlib/1.x"
