create-time = 1497389744
publish-time = 1369921722
avid = 584387
bvid = "BV1Qs411Z7yE"
title = "[洛天依重调版]风萤月本家PV"
category = "VOCALOID·UTAU"
desc-base64 = "6Ieq5Yi2IFvpo47okKTmnIhd5Y6f5Yib57uE5Yi25L2c77yaIOS9nOabsue8luabsuKAlOKAlHpvZXnvvJsg5L2c6K+N4oCU4oCU5Y+k6aOP5ZCN77ybIOatjOKAlOKAlOa0m+WkqeS+ne+8myDlm77igJTigJQxNeiTne+8myBQVuKAlOKAlOeZveipsOiNie+8myDkvIHliJLnm5HnnaPigJTigJTlsI/nqYbvvJsgTVAz5Zyw5Z2A77yaaHR0cDovL3NpdGUuZG91YmFuLmNvbS9oaWRlMTE1Ne+8m+mrmOa4heinhumikeS4i+i9ve+8muihpeWPkemrmOa4heeJiOWGhVBW77yaaHR0cDovL3Bhbi5iYWlkdS5jb20vc2hhcmUvbGluaz9zaGFyZWlkPTQ3MDc0MSZ1az0zNTkxMjg5MTcwIO+8m+WbvuWMhe+8mmh0dHA6Ly90LmNuL3pIS2M4Z2U="
[[parts]]
cid = 864427
name = ""
length = 319
resolution = "640x360"

[uploader]
uid = 162548
name = "月蝕原創音樂"

[snapshot]
snapshot-time = 1614840909.6786032
danmakus-count = 4183
likes-count = 8404
favorites-count = 2172
snapshot-by = "moe.lty.bgetlib/1.x"
