create-time = 1613245401
publish-time = 1613275210
avid = 586628043
bvid = "BV1zz4y1U73v"
title = "【言和原创】发往春天的电波【永不消逝的电波同人曲】【言和中心拜年祭单品】"
category = "VOCALOID·UTAU"
desc-base64 = "4oCc55WZ5LiA5q6155S15rOi6aOe5pWj5a+w5a6H5Lit77yM6Z2Z5b6F5pyq5p2l5LiO5L2g55u46KeB44CC4oCdCgrov5nmmK/kuIDpppblhpnnu5nmnY7nmb3ng4jlo6vnmoTmrYzjgILmnY7nmb3ng4jlo6vmmK/jgIrmsLjkuI3mtojpgJ3nmoTnlLXms6LjgIvvvIjnlLXlvbHov5jmnInoiJ7liafnrYnvvInkuK3kuLvkurrlhazmnY7kvqDnmoTljp/lnovvvIzmmK/nuqLlhpvmnIDml6nnmoTmiqXliqHlkZjvvIwxOTM35bm05LuO5bu25a6J6KKr5rS+5b6A5LiK5rW35LuO5LqL5Zyw5LiL55S15Y+w5bel5L2c44CC5LuW5Zub5qyh6KKr5o2V77yM5Z2a6LSe5LiN5bGI44CC5pyA5ZCO55qE5LiA5qyh77yM5LuW5Li65LqG6YCS6YCB5pyA6YeN6KaB55qE5oOF5oql4oCU4oCU5pWM5Lq65rGf6Ziy6K6h5YiS4oCU4oCU6YCJ5oup5LqG5bCG5oOF5oql5Y+R6YCB5a6M5q+V77yM5pS+5byD5LqG6YCD55Sf55qE5ZSv5LiA5py65Lya44CC4oCm4oCmCuS7luWwsei/meagt+S6ieWIhuWkuuenku+8jOS/nemanOS6huS4gOWcuumHjeWkp+eahOiDnOWIqeOAgueEtuWQjuS7lueJuueJsuWcqDE5NDnlubTvvIzpu47mmI7liY3nmoTmnIDnu4jnmoTpu5HmmpfkuK3jgIIK4oCU4oCUCui/h+WOu+eahOS4gOW5tOaIkeS7rOe7j+WOhuW+l+WkquWkmu+8jOS7v+S9m+S4gOW5tOmXtOe7j+WOhuS6huacgOeCveeDiOeahOaBqOS4jueIse+8jOacgOa3seayieeahOe7neacm+WSjOW4jOacm++8jOacgOeMm+eDiOeahOatu+S6oeS4jumHjeeUn+OAguS9hueMm+eEtuWbnummlu+8jOi/meS6m+aEn+aDheWFtuWunuaXqeW3sumVjOWIu+WcqOaIkeS7rOeahOmqqOmrk+S4re+8jOayiea3gOWcqOaAneaDs+mHjOOAguWcqOWygeaciOmdmeWlveaXtuWug+S7rOS7v+S9m+ayieWvgu+8jOWcqOmjjuS6keivoeiwsumXtOWNtOeerOmXtOi/uOWPke+8jOWum+WmguS4gOmil+eBq+enje+8jOeCueeHg+aIkeS7rOeahOeDreihgOOAggrkuIDlubTmnaXlpoLmraTvvIzljYHlubTmnaXlpoLmraTvvIznmb7lubTmnaXkuqbmmK/lpoLmraTjgIIK5L2T6aqM5Yiw6L+Z5Lqb5oOF5oSf5LiO57K+56We55qE5oiR5Lus77yM5a6a5pyJ5Yi56YKj6Ze05oSf5Y+X5Yiw5LqG5LuW5Lus55qE5pyf5b6F5LiO5biM5pyb44CC5bCx5q2k77yM5oiR5Lus5bu257ut5LqG5LiA55m+5bm05Lul5p2l5LuW5Lus55qE5L+h5Luw5LiO54G16a2C44CCCuiuqeaIkeS7rOWKquWKm+WcsOeUn+a0u+S4i+WOu+WQp++8geeEtuWQjuS7luS7rOWwhuS8muWcqOaIkeS7rOeahOeUn+WRveS4reawuOe7reeUn+a0u+edgO+8gQoK55uR5Yi277ya6Z2S5YalIOmFkuWxseWEvwrmm7Iv57yWL+a3t+mfsy/mm7Lnu5jvvJrovabliY3ojYkK6K+NL+iwgy/mr43luKbvvJrlub3lr4IK6KeG6aKR77ya5q+b6IW/54yq5YWU5a2QCgoyMDIx5bm06KiA5ZKM5Lit5b+D5ouc5bm056Wt5pys5a6277yaQlYxOHk0eTFZN3ZwCuabtOWkmueahOW5veWvguWSjOi9puWJjeiNie+8mua1t+eHle+8iEJWMUp4NDExeDdUeO+8iSDpo47pm6jlvoHnqIvvvIhCVjFMSjQxMXE3VlHvvIkg5Y2D5bm05rKn5rW35LiK77yIQlYxTDc0MTFyNzFI77yJCuabtOWkmueahOavm+iFv+eMquWFlOWtkO+8muaRhOezlnRoZXJhcHnvvIhCVjFFdDQxMWE3SnnvvIk="
[[parts]]
cid = 297336807
name = "发往春天的电波"
length = 275
resolution = "1920x1080"

[[staff]]
favorite-time = 12450
uid = 3230866
title = "UP主"
name = "前草"

[[staff]]
favorite-time = 12450
uid = 478860
title = "作词"
name = "幽寂"

[[staff]]
favorite-time = 12450
uid = 2036555
title = "视频制作"
name = "毛腿猪兔子"

[[staff]]
favorite-time = 12450
uid = 409286974
title = "策划"
name = "岁岁言言人又同"

[uploader]
uid = 3230866
name = "前草"

[snapshot]
snapshot-time = 1614840866.4553773
danmakus-count = 69
likes-count = 1101
favorites-count = 1415
snapshot-by = "moe.lty.bgetlib/1.x"
