create-time = 1497423797
publish-time = 1364745461
avid = 521166
bvid = "BV1Lx411c7cT"
title = "【洛天依打吊针】摩的大飚客(公婆版歌词)【跳蝻P】【FlashPV】"
category = "VOCALOID·UTAU"
desc-base64 = "44CQ55m96YeR5aSp5L2/44CR6IGU5Yqo4oaSIGF2NTIzMTg0IOKGkCDpppblhYjmhJ/osKJMaWx5c2NhcuaPkOS+m+S8tOWlj+OAgeS7peWPikF5YeWPlOWPlOacrOiJsuOBruabsue7mO+8geatjOivjeaYr+WFrOWphueJiCDlhbblrp7miJHnn6XpgZPpo5novabnmoTmmK/lkLTlhYvvvIHvvIHmgLvkuYvvvIHov5npppbmiZPlkIrpkojlrp7lnKjlpKrniL3kuoYg5LiN57+75pyJ5oKW5aSp55CG5ZWK77yB5LiA5aSp5a6M5bel55qE5LiN6KaB5Zyo5oSP6LSo6YeP77yB44CQ5LiL6L295Zyw5Z2A44CRaHR0cDovLzVzaW5nLmt1Z291LmNvbS82ODM3Njc="
[[parts]]
cid = 779853
name = ""
length = 173
resolution = "634x360"

[uploader]
uid = 379803
name = "跳蝻T-Nymph"

[snapshot]
snapshot-time = 1614840815.7815864
danmakus-count = 7839
likes-count = 14318
favorites-count = 3140
snapshot-by = "moe.lty.bgetlib/1.x"
