create-time = 1564021380
publish-time = 1564021380
avid = 60660066
bvid = "BV1jt411j7Yu"
title = "【洛天依原创】haru【手书pv】"
category = "VOCALOID·UTAU"
desc-base64 = "5ZSx77ya5rSb5aSp5L6dCuivjeabsu+8mkNPUArop4bpopHvvJrllK9UdQrlsI/mj5DnkLTlrp7lvZXvvJp5dWd1cmUKCuW5tOabtOaIkOWwse+8iDEvMe+8iQrovpvoi6blhZTlk6Xlk6XnmoRwduWSjHl1Z3VyZeeahOWunuW9le+8gQrorrLkuoblhbPkuo7luIzmnJvkvKDpgJLnmoTmlYXkuovvvIzot6/pgJTlpJroiJvkuZ/lv4XpobvliY3ooYzjgIIK5oiR5oOz5aSn5a626YO955+l6YGT6L+Z5Liq5pys5p2l6K+l5ZOq5aSp5oqV55qE77yM5Y+v5Lul6KOF5L2c5LiN55+l6YGTwrfCt8K3wrfCtwrmnIDlkI7nu5nlpKflrrbmi5zlubTkuobvvIzkuIvkuKrkuIPmnIjmnaHljobmlrDlubTlho3op4HvvIE="
[[parts]]
cid = 105565594
name = "合成 19"
length = 231
resolution = "1920x1080"

[uploader]
uid = 396194
name = "COPY"

[snapshot]
snapshot-time = 1614840845.5806382
danmakus-count = 879
likes-count = 11378
favorites-count = 13368
snapshot-by = "moe.lty.bgetlib/1.x"
