create-time = 1497427656
publish-time = 1486137600
avid = 7445327
bvid = "BV1Ns411e7Eq"
title = "【2017元宵】相声·大话星尘（乐正绫×星尘）"
category = "VOCALOID·UTAU"
desc-base64 = "55u45aOwIOOAiuWkp+ivneaYn+WwmOOAi+OAkOWOn+WIm+OAkQrliafmnKwm6LCD5pWZ77yaTW9rdXJlacK35pyo54G15ZCbCuS6uuiuvueUu+W4iO+8mkDkuInllpxQCuiDjOaZr+eUu+W4iO+8mkDlpKfmoLnolYkKCuayiea3gOS6huWwhui/keS4gOW5tOeahOivreiwg+S9nOWTgeOAggrlhbblrp7ov5npg6jnm7jlo7DnmoTnqL/lrZDlnKjmiJEy5pyI5Lu95YaZ5LiJ5Y+l5Y2K55qE5pe25YCZ5bCx5bey57uP5YaZ5aW95LqG77yM5YmN5YmN5ZCO5ZCO56255aSH5LqG5LiA5bm044CCCuato+WlveWcqOeni+Wkqeeci+WIsELnq5nlhYPlrrXmmZrkvJrnmoTlvoHnqL/lronliKnkuabvvIzkuo7mmK/kuIDpvJPkvZzmsJTmiorov5npg6jnm7jlo7DlrozmiJDkuobvvIzov5nkuZ/mmK/kuIDpg6jnu4/ov4flpKfph4/liKDmlLnogIzliJvkvZznmoTkvZzlk4HjgIIK5biM5pyb5aSn5a626IO95aSf5Zac5qyi77yM5Lmf5biM5pyb5LuK5ZCO6IO95bim57uZ5aSn5a625pu05aSa55qE5qyi5LmQ77yBCuato+WAvOWygeacq++8jOaIkeWcqOi/memHjOe7meWkp+WutuaLnOS4quaXqeW5tO+8jOelneWkp+Wutum4oeW5tOWkp+WQie+8gQoK5pyo54G15ZCbIOS6jjIwMTblubQxMuaciDnml6UgCg=="
[[parts]]
cid = 12177034
name = ""
length = 449
resolution = "640x360"

[uploader]
uid = 3220126
name = "Mokurei·木灵君"

[snapshot]
snapshot-time = 1614840804.76151
danmakus-count = 5216
likes-count = 9627
favorites-count = 2713
snapshot-by = "moe.lty.bgetlib/1.x"
