create-time = 1613818077
publish-time = 1613818077
avid = 714362023
bvid = "BV1BX4y1G7GY"
title = "【乐正绫翻唱】不问天"
category = "VOCALOID·UTAU"
desc-base64 = "5pys5a6277yaQlYxc3Y0eTFmN1EyCuS8geWIku+8muW5s+WuieWknOeahOWZqeaipgrkvZzmm7LvvJpwYXBhd+azoeazoQrkvZzor43vvJpWYWdhcnkK5Y6f5ZSx77ya6K+06K+0Q3J5c3RhbAoK5oSf6KeJ5bey57uP5aW95LmF5LiN56Kw57yW6L6R5Zmo5LqG77yM5omL5Y+N5q2j5piv6LaK5p2l6LaK55Sf77yM5bCx6L+Z5qC35ZCn77yM5omA5Lul6L+Z5Lik5aSp5bCx6ZqP5L6/5pG45pG46bG8fuavleern+aIkei/mOimgeW/meedgOaJk++8iHdh77yJ5ri477yIeGlu77yJ5oiP77yIa2VuZ++8ieWPl++8iGxhae+8iemavu+8iGd177yJfg=="
[[parts]]
cid = 300244208
name = "【乐正绫翻唱】不问天"
length = 257
resolution = "1920x1080"

[uploader]
uid = 893950
name = "纳兰寻风"

[snapshot]
snapshot-time = 1614839976.1185343
danmakus-count = 84
likes-count = 2149
favorites-count = 4426
snapshot-by = "moe.lty.bgetlib/1.x"
