create-time = 1612576324
publish-time = 1612951205
avid = 714069843
bvid = "BV12X4y1N79n"
title = "【心华六周年生贺曲】心话 2021ver.【原创PV付】"
category = "VOCALOID·UTAU"
desc-base64 = "MS7mipXnqL/kuo7pq5jogIPliY3kuIDnmb7kvZnml6XkuYvpmYXvvIzkuLTogIPliY3mnIDlkI7kuIDkvZzvvIjogZTmipXkuYvlpJbvvInjgIIKMi7lhaXlnZFWQ+aYr+WcqOWIneS4ieWvkuWBh++8jOWmguS7iua7oea7oeS4ieW5tOOAguWbnuaDs+mrmOS4reeUn+a2r++8jOedgOWunuS4jlZD55u45L6d6Imv5LmF44CCVkPkvLTmiJHliY3ooYzvvIzmiJHlkIxWQ+ivieivtOOAggozLuS4pOW5tOWJje+8jOW/g+ivnSAyMDE5dmVyLu+8iEJWMXBiNDExUzdqeu+8ieaKleeov++8jOaYr+aZmumSn+esrOS4gOmmluW/g+WNjuabsuOAguS4gOW5tOWJje+8jOW/g+ivnSAyMDIwdmVyLu+8iEJWMVA3NDExNjc2Z++8ieaKleeov++8jOaYr+aZmumSn+esrOWbm+mmluW/g+WNjuabsuOAguWmguS7iu+8jOW/g+ivnSAyMDIxdmVyLu+8iOacrOabsu+8ieaKleeov++8jOaYr+aZmumSn+esrOS5nemmluW/g+WNjuabsuOAguaIkeeIseW/g+WNju+8jOS7juOAiuaYn+mbqOS5i+WknOOAi+W8gOWni++8jOiAjOWFtuS4reaJgOiVtO+8jOWHoOS5juWHuueOsOWcqOaIkeeahOavj+S4gOmmluW/g+WNjuabsuS4reOAggo0LuacrOabsuiZveivtOaYr+e/u+Whq++8iOW/g+ivnTIwMTnjgIHlv4Por50yMDIw5Lmf5piv57+75aGr77yM5byV5Li65oOv5L6L77yJ77yM5L2G6Zmk5LqG5puy5LmL5aSW6YO95piv6auY6YWN5Y6f5Yib44CC5Y6f5puy6K+N5puy5L2c6ICF6Iqx6Ze05ri45LiO5YeL6Zu26JGJ6YO95piv5aW95Y+L77yM6Iqx6Ze05LiN5oOf5LqI5Lul5o6I5p2D77yM6L+Y5Y6a6LS25pys5puy77yM5Zyo5q2k5rex6KGo6LCi5oSP44CCCjUu5oSf6LCi6aOO6ZOD6ICB5biI6Jm96K++5Lia57mB6YeN5LuN6LCD5a6M5q2k5puy77yM5oSf6LCi5Y+j5Y+j6ICB5biI54iG6IKd55qE57K+576O5puy57uY77yM5aCq56ew5a6M576O5YiH5ZCI6K+N5aKD44CCCjYu5q2M6K+N5omA57uY77yM5piv5bCP6ZWH5YGa6aKY5a6255qE5oKy5oOo5LiW55WM44CC5Zyo5YWo5Zu95LiA5Y2377yIanVhbjPvvInlnLDljLrnlJ/lrZjvvIznoa7lrp7pnIDopoHmnoHpq5jnmoTljbflipvlrabotovlir/jgIIKNy7kvYbmmK/lpoLmnpzmipvljrvog4zmma/vvIzpgqPkuYjmrYzor43ov5jmmK/lj6/ku6XkvZzkuLrkvJjnvo7nmoTnlLvljbflk4HlkbPnmoTjgILov5nlsLHmmK/oibrmnK/liqDlt6XjgIIKOC7otbfliJ3mmK/mg7PlsLHnnYDlv4PljY7lj5HmjKXnmoTvvIzlkI7mnaXkuI3nn6XpgZPmgI7kuYjlsLHlhpnmiJDov5nmoLfkuobjgILlj6/og73mmK/lj5fmnZznlKvjgIrlgbbpopjjgIvlvbHlk43jgIIKOS5iYW5nMTXkvr/lo6sK5ryU5ZSx77ya5b+D5Y2OCuWSjOWjsO+8muS5kOato+e7qwrnrZbliJLvvJrmmZrpkp8K5Y6f5puy57yW77ya5YeL6Zu26JGJCuWOn+ivjeS9nO+8muiKsemXtOa4uArnv7vloavor43vvJrmmZrpkp8K6LCD5re377ya55m95ryq6aOO6ZODCuabsue7mO+8muWPo+WPowrmmKDnlLvvvJrotorlpKnmmKDnlLsK55uR5Yi277ya6Iqx6Ze05ri4CuWwgemdouWItuS9nO+8muiKsemXtOa4uArlsIHpnaLpopjlrZfvvJrmmZrpkp8K5qCH6aKY5ouf5YaZ77ya5pmo55Cb5ZCb"
[[parts]]
cid = 295034974
name = "心话2021"
length = 201
resolution = "1920x1080"

[[staff]]
favorite-time = 12450
uid = 303165863
title = "UP主"
name = "风雨夕阳-晚钟"

[[staff]]
favorite-time = 12450
uid = 14414682
title = "曲绘"
name = "全是坑的八百亩口口"

[[staff]]
favorite-time = 12450
uid = 4037580
title = "策划"
name = "花间有鹿来"

[[staff]]
favorite-time = 12450
uid = 773253
title = "调校"
name = "白漪风铃"

[[staff]]
favorite-time = 12450
uid = 487667737
title = "视频制作"
name = "越天映画"

[uploader]
uid = 303165863
name = "风雨夕阳-晚钟"

[snapshot]
snapshot-time = 1613319895.4453459
danmakus-count = 1
likes-count = 234
favorites-count = 342
snapshot-by = "moe.lty.bgetlib/1.x"
