create-time = 1612534999
publish-time = 1612534999
avid = 714093644
bvid = "BV1MX4y157jW"
title = "【钢琴】百戏人间"
category = "演奏"
desc-base64 = "5pys5a6277yaQlYxZDU0eTFyNzdnCuacrOWutnN0YWZm77yaCuetluWIku+8muWHnembque/vArkvZzmm7LvvJpwYXBhd+azoeazoQrnvJbmm7LvvJpwYXBhd+azoeazoQrkvZzor43vvJpWYWdhcnkK6LCD5qCh77ya57qz5YWw5a+76aOOCua8lOWUse+8mua0m+WkqeS+nQrlkI7mnJ/mt7fnvKnvvJrlhqzlrZAK4oCU4oCU4oCU4oCU4oCU4oCUCue/u+WUseeJiO+8mkJWMWo1NHkxVzdtbg=="
[[parts]]
cid = 293369598
name = "【钢琴】百戏人间"
length = 246
resolution = "1920x1080"

[uploader]
uid = 128548736
name = "逆卷一多"

[snapshot]
snapshot-time = 1612901943.0725493
danmakus-count = 1
likes-count = 18
favorites-count = 57
snapshot-by = "moe.lty.bgetlib/1.x"
