create-time = 1598512896
publish-time = 1598512896
avid = 711913134
bvid = "BV1VD4y1m7Px"
title = "跨越千年再回春秋！听一首歌叹《吴王》的绝美音乐「迟暮」&「洛天依/乐正绫」"
category = "VOCALOID·UTAU"
desc-base64 = "5Liq5Lq656ys5LqU6aaW5Y6f5Yib5q2M5puy44CK6L+f5pqu44CL57uI5LqO5ZKM5aSn5a626KeB6Z2i5ZWm44CCCuacrOasoeWIm+S9nOi/mOaMuuWdjuWdt++8jOWJjeWQjuaMgee7reS6huacieS4gOW5tOWkmueahOaXtumXtO+8jOaJjeacgOe7iOWujOeov+OAggrov5npppbmrYzmmK/lkozljrvlubTliJ3mipXnqL/nmoTjgIrllqflmrfjgIvlkIzmnJ/liJvkvZznmoTvvIzlnKjlhpnnmoTml7blgJnnnYDph43mg7PkvZPnjrDkuIDnp43kuI3nlJjlkozmgrLlj7nnmoTmg4Xnu6rvvIzku6Xlj4rlhpnpl7TlpY/nrJvlrZDkuIDpq5jkuI7lkI7mrrXnkLXnkLbkuIDkvY7ov5nmoLfnmoTphY3lkIjvvIzpg73kuLrkvZPnjrDov5nmrKHnlLHmtJvlpKnkvp3lkozkuZDmraPnu6vliIbliKvmia7mvJTnmoTlkLTnjovlpKvlt67kuIDog5zkuIDoobDnmoTkuLvpopjjgIIK5LiW5Lq655qG55+l6LaK546L5Y2n6Jaq5bCd6IOG55qE5pWF5LqL77yM5L2G6L+Z5LiA5qyh77yM5oiR5oOz55So6L+Z5Liq6KeG6KeS5Y675o+P57uY5pu+57uP55qE6Zy45Li75ZC0546L77yM5Lmf6K6p5aSn5a625Y+v5Lul5pu05LqG6Kej6L+Z5qC35LiA5Liq6KeS6Imy44CCCuS9nOivjeaWuemdou+8jOS+neeEtuaYr+WSjOWGpeWHsOWkp+Wkp+eahOWQiOS9nO+8jOi/measoeeahOivjeWcqOaIkeivu+S6huWlveWHoOmBjeS7peWQju+8jOS+neeEtuiDveaEn+WPl+WIsOavj+Wtl+avj+WPpeW4pue7meaIkeeahOeUu+mdouWSjOmch+aSvOaEn++8jOmfs+S5kOWSjOatjOivjeacieaXtuWAmeWwseaYr+i/meS5iOWlh+Wmme+8jOS7v+S9m+iuqeaIkeecn+WunueahOWcqOmCo+auteepuumXtOWOhuWPsuS4rea4uOWOhuS6huS4gOWbnuS8vOW+l++8jOi6q+S4tOWFtuWig+OAggrnhLblkI7mhJ/osKLlsI/ompXjgIHog6fjgIHpn7PnrKbjgIHlubrllKDnrYnlpKflpKflnKjmnKzkvZzkuK3nmoTku5jlh7rvvIzku6Xlj4rnp4vnu5jlnKjlkozlo7DmvJTnu47mlrnpnaLnmoTlh7roibLooajnjrDvvIzov5jmnInmt7fpn7PmlrnpnaLnmoTml6DpmZDvvIjkuI3vvInmrKHmnaXlm57pgIDkv67vvIzku6Xlj4rlj4LkuI7lrp7lvZXlkozop4bpopHmlrnpnaLliLbkvZznmoTlpKflpKfku6zov5jmnInmnY7ogIHluIjluK7lv5nnmoTkuIDkupvkurrlkZjmjqjojZDvvIEK5aSn5a625LiA5a6a6KaB57uZ5oiR5Lus5oqV5biB5ZOm77yB77yB77yB5biM5pyb5Lul5ZCO6IO957un57ut57uZ5aSn5a625bim5p2l5pu05aW955qE5L2c5ZOB77yBCgpTVEFGRgrnrZbliJIv55uR5Yi277ya5pqX54yr44Gu56Wd56aPCgrkvZzmm7LvvJrmmpfnjKvjga7npZ3npo8K5L2c6K+N77ya5Yal5YewCue8luabsu+8muS4g+WIhumfs+espu+8iOi4j+S6keekvu+8iQoK5YiG6L2o5re36Z+z77ya5bm65ZSgXwrmr43luKbvvJrog6cK5ZKM5aOw57yW5YaZ77ya6IOnCgrmvJTllLHvvJrmtJvlpKnkvp0m5LmQ5q2j57urClblrrbosIPmlZnvvJrlkajlsI/ompUK5ZCI5aOw5ryU5ZSx77yaQWtpZeeni+e7mAoK5Y+k562d77ya5aKo6Z+1TW95dW4K56yb77ya5rC0546l5YS/CueUteWQieS7lu+8muiDpwrmnKjlkInku5bvvJpMYWxhY29vcGVyCgrnvo7mnK/vvJpMIVNURU7vvIjllrXlpKrnpL7vvIkKUFbvvJroib7ms6DvvIjllrXlpKrnpL7vvIk="
[[parts]]
cid = 229395530
name = "迟暮V家版本"
length = 242
resolution = "1920x1080"

[[staff]]
favorite-time = 12450
uid = 888465
title = "UP主"
name = "暗猫の祝福"

[[staff]]
favorite-time = 12450
uid = 5798
title = "作词"
name = "冷鸟"

[[staff]]
favorite-time = 12450
uid = 15735857
title = "编曲"
name = "七分音符_TY"

[[staff]]
favorite-time = 12450
uid = 4218714
title = "混音"
name = "幺唠_"

[[staff]]
favorite-time = 12450
uid = 10996289
title = "调校"
name = "周小蚕"

[[staff]]
favorite-time = 12450
uid = 4176573
title = "演唱"
name = "Akie秋绘"

[[staff]]
favorite-time = 12450
uid = 32806702
title = "母带"
name = "胧音_Long"

[[staff]]
favorite-time = 12450
uid = 917355
title = "演奏"
name = "水玥儿"

[[staff]]
favorite-time = 12450
uid = 2632731
title = "曲绘"
name = "喵太社"

[[staff]]
favorite-time = 12450
uid = 2099852
title = "视频制作"
name = "艾泠Aileen"

[uploader]
uid = 888465
name = "暗猫の祝福"

[snapshot]
snapshot-time = 1613661610.2355988
danmakus-count = 800
likes-count = 36685
favorites-count = 48666
snapshot-by = "moe.lty.bgetlib/1.x"
