create-time = 1612917258
publish-time = 1612917258
avid = 844031164
bvid = "BV1j54y1W7g3"
title = "【洛天依原创】周末 Weekend【PV付】【QGRay】"
category = "VOCALOID·UTAU"
desc-base64 = "5ZWm5ZWm5ZWm77yM5ZKV5LqG6L+Z5LmI5LmF5LqG77yM57uI5LqO5Y+R4oCc6bi94oCd5LqGfn4KCue8luabsi/mt7fpn7Mv5L2c6K+NL+S9nOabsi/osIPmlZkv5puy57uYL1BWL+WQjuacn++8mlFHUmF5CgpQVuWBmueahOS4jeeul+W+iOWlve+8jOiHquW3seiHquWtpuWBmueahO+8jOWLieW8uuiDveeci+WQpzB2MAoK572R5piT5LqR6Z+z5LmQQFFHUmF5CuabsuWQje+8mldlZWtlbmQK6ZO+5o6l77yaaHR0cHM6Ly9tdXNpYy4xNjMuY29tLyMvc29uZz9pZD0xODE5MTM3OTk0CgrmnIDlkI7npZ3lpKflrrbmlrDlubTlv6vkuZB+fn4="
[[parts]]
cid = 295665206
name = "Weekend"
length = 238
resolution = "1920x1080"

[uploader]
uid = 393416910
name = "奇怪雷子QGRay"

[snapshot]
snapshot-time = 1614840788.7582202
danmakus-count = 13
likes-count = 311
favorites-count = 470
snapshot-by = "moe.lty.bgetlib/1.x"
