create-time = 1609588811
publish-time = 1609588806
avid = 843408485
bvid = "BV1454y1x7S5"
title = "【星尘Minus/海伊/诗岸】秦淮景【吴侬软语】"
category = "VOCALOID·UTAU"
desc-base64 = "5Y+I5Yiw5LqG5paw5bm056ys5LiA56i/77yM5b2T54S26KaB5oqV5rCR5q2M5ZWmfgrov5nmrKHor5Xkuobor5Xoi4/lt57or4TlvLnvvIzorqnkuInkuKrlsI/lprnlprnlvZPkuIDlm57msZ/ljZfmrYzlpbMKCuatjOabsu+8muenpua3ruaZr++8iOeUteW9seOAiumHkemZteWNgeS4iemSl+OAi+S4u+mimOabsu+8iQrnv7vllLHvvJrmmJ/lsJhNaW51cy/mtbfkvIov6K+X5bK4Cuiwg+aVme+8mueRnuWuiVJ5YW7kuI3ot5HosIMK6KeG6aKR77ya55Ge5a6JUnlhbuS4jei3keiwgwoK5rCR5q2M6K6h5YiS77yaCkJWMXF0NDExeDdFWSDkuZDmraPnu6sgLSDotbDopb/lj6MKQlYxTUo0MTFiN0tKIOiLjeepuSAtIOiOq+WwvOWxsQ=="
[[parts]]
cid = 275806140
name = "【星尘Minus-海伊-诗岸】秦淮景【吴侬软语】"
length = 106
resolution = "1920x1080"

[uploader]
uid = 108845996
name = "瑞安Ryan不跑调"

[snapshot]
snapshot-time = 1614839991.0009954
danmakus-count = 73
likes-count = 2228
favorites-count = 3308
snapshot-by = "moe.lty.bgetlib/1.x"
