create-time = 1612916159
publish-time = 1612916159
avid = 801541909
bvid = "BV11y4y1n7KE"
title = "【心华生快】华歌【Vocaloid原创曲】"
category = "VOCALOID·UTAU"
desc-base64 = "5pe26Ze055yf5piv5b+r5ZWK77yM6Led56a75oiR56ys5LiA5qyh5ZCs6KeB5b+D5Y2O55qE5aOw6Z+z5bey57uP6L+H5LqG5b+r5LqU5bm05LqG77yM5byA5aeL5L2c5puy5Lmf5pyJ5Zub5bm05aSa5LqG44CC5L2G56ys5LiA5qyh6KKr5b+D5Y2O5omA5omT5Yqo77yM5b+D6YeM54eD6LW35LiA56eN5oOz5Li65b+D5Y2O5YaZ5q2M55qE5r+A5oOF55qE5Zy65pmv77yM5LuN6IO95pe25LiN5pe25oOz6LW377yI6K6w5b6X5b6I5riF5qWa77yM5b2T5pe25Zyo5ZCs44CK5bCR5aWz5b+D6K+t44CL77yJ44CCCgrlpbPlranorqnkuIDkuKrml6DotqPnmoTkurrniLHkuIrkuobpn7PkuZDvvIzmnIDlkI7miJDkuLrkuobku5bnlJ/mtLvkuK3kuI3lj6/nvLrlsJHnmoTkuIDpg6jliIbvvIzlr7nku5bmnaXor7TvvIzov5nku7bkuovmmK/ml6Dlj6/mm7/ku6PnmoTlrp3ol4/jgILov5npppbmrYzvvIzorrLnmoTlsLHmmK/ov5nmoLfkuIDkuKrnroDljZXogIHlpZfnmoTvvIzku5blkozlpbnnmoTmlYXkuovigJTigJTmiJHlkozlv4PljY7nmoTmlYXkuovvvIzmiJborrjkuZ/mmK/orrjlpJrkurrkuI7lv4PljY7nmoTmlYXkuovjgIIKCuivjeabsue8luiwg++8jOabsue7mFBW77ya5a+S5pyIRXBoZW0KCuW/g+WNju+8jOeUn+aXpeW/q+S5kF7PiV4="
[[parts]]
cid = 295632080
name = "心华2021_2"
length = 275
resolution = "1980x1080"

[uploader]
uid = 35878442
name = "寒月Ephem"

[snapshot]
snapshot-time = 1613319846.971856
danmakus-count = 1
likes-count = 31
favorites-count = 39
snapshot-by = "moe.lty.bgetlib/1.x"
