create-time = 1579256737
publish-time = 1579256737
avid = 83828800
bvid = "BV1qJ411E7Qo"
title = "【洛天依】跨越次元的愿想！原创曲《遥远的相遇》送给屏幕前的你。"
category = "VOCALOID·UTAU"
desc-base64 = "4oCc6L+Z6aaW5q2M55yf55qE5piv5LiA6aaW5b6I5LqM5qyh5YWD55qE5q2M44CC4oCdCuKAnOaIkeW4jOacm+i/memmluatjOiDveiuqeabtOWkmuS6uuWWnOasolblrrbjgILigJ0K6L+Z6aaW5q2M55qE5Yib5L2c5Li76aKY5piv5Zu057uV552A5Zyo5LiN5ZCM55qE5qyh5YWD55qE5Lik5Liq5Lq677yM5Zyo5qKm6YeM55u45LqS6YGH6KeB5Yiw5a+55pa577yM54S25ZCO5Zue5Yiw546w5a6e5Lit5Lmf6L+Y5oCd5b+1552A6L+Z5Lu954m55q6K55qE576B57uK77yM5oOz6KaB5Yay56C05bGP6Zqc5YaN5qyh55u46YGH6L+Z5LmI5LiA5Liq5Li76aKY44CCCuWvueS6juWkqeS+neadpeivtO+8jOS7juiZmuaLn+atjOaJi+adpeiusu+8jOaYr+ivieivtOedgO+8jOa8lOWUseedgO+8jOWPpuS4gOS4quasoeWFg+eahOaVheS6i+OAggrlr7nkuo7miJHkuKrkurrmnaXor7TvvIznvZHnu5zkuIrnmoTmmpfnjKvvvIzmiJborrjlsLHmmK/lvojlpJrkurrlv4Pph4znmoTlj6bkuIDkuKromZrmi5/lvaLosaHvvIzmiJHop4nlvpfov5npppbmrYzkuZ/mmK/lhpnnu5nllpzmrKLmiJHnmoTnsonkuJ3nmoTvvIzmnInlvojlpJrkuZ/mmK/miJHnmoTlv4Plo7DvvIzlvJXnlKjmiJHlnKjnvZHmmJPkupHkuJPovpHkuIrlhpnnmoTor53kuIDmoLcKCuOAjOaIkeaXtuW4uOWcqOaDs++8jOWmguaenOacieS4gOWkqeaIkeeqgeeEtuWcqOe9kee7nOS4iuayoeacieS6huiur+aBr++8jOmCo+W6lOivpeeVmeS4i+aAjuagt+eahOW/g+WjsOaJjeWPr+S7peiuqeS9oOS7rOawuOi/nOeahOiusOW+l+aIkeeahOWtmOWcqOOAggrnjrDlnKjvvIzmnInkuobov5npppbmrYzvvIzpgqPlsLHlpJ/kuobjgIIK4oCc5L2g5Lya5rC46L+c5Zac5qyi5oiR5ZCXLi4u4oCdCuKAnOS9oOS8muawuOi/nOiusOW+l+aIkeWQly4uLuKAnQrkuI3nrqHmgI7moLfvvIzkvaDpg73kvJrlnKjmn5DlpITpmarkvLTnnYDmiJHnmoTlkKfjgIIK6ICM5Y+q6KaB5oiR6L+Y5a2Y5Zyo77yM5Lmf5LiA5a6a5Lya5YGa5b6I5aSa5Lic6KW/5Yqq5Yqb55qE6Zmq5Ly0552A5L2g5Lus55qE44CC44CNCgrmm7Lpo47lkozosIPmlZnkuIrvvIznibnliKvmmK/osIPmlZnmiJHnibnmhI/mg7PopoHmtJvlpKnkvp3pgqPnp43nlLXlrZDpn7PpnLLlh7rmnaXnmoTlpJrkuIDkupvvvIzpgqPlkozov5npppbmrYzmlbTkvZPnmoTmhI/looPkvJrmm7TliqDmkK3phY3kuIDkupvjgIIK5ZKM6IOn5Zyo5q2M5puy5ZCI5L2c5LiK6L+Y5piv6Z2e5bi45oSJ5b+r55qE77yM6Jm954S25L+u5pS55LqG5Y+v6IO95pyJMzDlpJrniYjvvIhoaGjvvInkvYbmmK/kuLrkuobmg7PopoHnmoTotKjph4/lkoznsr7luqbvvIzlpKflrrbpg73nnJ/nmoTlvojovpvoi6blkaLjgIIK5Lmf5oSf6LCi5YWr6YeM6IO955S75Ye66L+Z5LmI5aSa5byg5ryC5Lqu55qE5Zu+77yM5YW25LuW55qE5bCx5LiN5aSa6K+05ZWm77yM5oC75LmL5piv5LiA5qyh6Z2e5bi45byA5b+D55qE5ZCI5L2c77yM6YKj5Lmf5biM5pyb6Ieq5bex5pyq5p2l6IO95YaZ5Ye65pu05aSa5aW95ZCs55qE5q2M77yM6K6w5b6X5LiJ6L+e5ZmiCgrjgIrpgaXov5znmoTnm7jpgYfjgItTVEFGRgrkvIHliJIv55uR5Yi277ya5pqX54yr44Gu56Wd56aPCgrkvZzmm7Ig5pqX54yr44Gu56Wd56aPIOiDpwrkvZzor40g5p6c5rGB5YeJ6I+cIArnvJbmm7Iv5re36Z+zIOiDpwoK5ryU5ZSxIOa0m+WkqeS+nQrosIPmlZkg5ZGo5bCP6JqVCuWSjOWjsCDog6cKCuabsue7mCDlhavph4zvvIjllrXlpKrnpL7vvIkKcHYg6Im+5rOgIOi0vuWbm+S4gO+8iOWWteWkquekvu+8iSDmmpfnjKvjga7npZ3npo8K5Ye65ryUIOaal+eMqwoK5LiK5LiA5L2c5rSb5aSp5L6d55qE5q2M77yaYXYzOTg2ODkwOA=="
[[parts]]
cid = 143416894
name = "遥远的相遇PV2"
length = 359
resolution = "1920x1080"

[[staff]]
favorite-time = 12450
uid = 888465
title = "UP主"
name = "暗猫の祝福"

[[staff]]
favorite-time = 12450
uid = 32806702
title = "编曲"
name = "胧音_Long"

[[staff]]
favorite-time = 12450
uid = 1629850
title = "作词"
name = "果汁凉菜"

[[staff]]
favorite-time = 12450
uid = 10996289
title = "调校"
name = "周小蚕"

[[staff]]
favorite-time = 12450
uid = 2632731
title = "曲绘"
name = "喵太社"

[[staff]]
favorite-time = 12450
uid = 1719747
title = "视频制作"
name = "贾四一"

[[staff]]
favorite-time = 12450
uid = 2099852
title = "视频制作"
name = "艾泠Aileen"

[uploader]
uid = 888465
name = "暗猫の祝福"

[snapshot]
snapshot-time = 1614840876.2754629
danmakus-count = 2363
likes-count = 25682
favorites-count = 33607
snapshot-by = "moe.lty.bgetlib/1.x"
