create-time = 1611670864
publish-time = 1611670864
avid = 843820459
bvid = "BV1c54y1x7Rv"
title = "【洛天依原创曲】自由的蚂蚁"
category = "VOCALOID·UTAU"
desc-base64 = "6JCM5paw56ys5LiA5qyh5YaZVuabsnF3cQrkvZzmm7I65a6B5qqsKExlbW9uX05pbmcpCuS9nOivjTrlroHmqqwoTGVtb25fTmluZykK57yW5puyOuWugeaqrChMZW1vbl9OaW5nKQrmt7fpn7M65a6B5qqsKExlbW9uX05pbmcpClAgViA65a6B5qqsKExlbW9uX05pbmcpICjlroHnrqHov5nlj6tQVj8/PykK57uZ5Liq5YWz5rOo5Yqg5LiJ6L+e5ZCnIOODvijvv6Pilr3vv6Mp"
[[parts]]
cid = 288072992
name = "自由的蚂蚁_1_1_1"
length = 285
resolution = "1920x1080"

[uploader]
uid = 229042984
name = "宁檬_Lemon_Ning"

[snapshot]
snapshot-time = 1612502735.1733475
danmakus-count = 3
likes-count = 97
favorites-count = 127
snapshot-by = "moe.lty.bgetlib/1.x"
